import {useEffect,useRef,useState,type FormEvent} from 'react'
import {X,ArrowRight,Check} from 'lucide-react'
import type {Auth} from '../App'
import {api,createOperation,money,monthLabel,today} from '../api/client'
export const cents=(value:string)=>{const [whole,fraction='']=value.replace(',','.').split('.');return Number(whole)*100+Number((fraction+'00').slice(0,2))}
export function CommitmentForm({auth,onClose,onSaved}:{auth:Auth,onClose:()=>void,onSaved:()=>void}){
 const [cards,setCards]=useState<any[]>([]),[description,setDescription]=useState(''),[amount,setAmount]=useState(''),[count,setCount]=useState(1),[date,setDate]=useState(today()),[card,setCard]=useState(''),[buyer,setBuyer]=useState(auth.user.id),[payer,setPayer]=useState(auth.user.id),[firstMonth,setFirstMonth]=useState(today().slice(0,7)),[preview,setPreview]=useState<any>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false)
 const [custom,setCustom]=useState<Record<string,string>>({})
 const pending=useRef<(()=>Promise<any>)|null>(null),payload=useRef<any>(null)
 useEffect(()=>{api('/cards').then(setCards).catch(e=>setError(e.message))},[])
 function reset(){setPreview(null);pending.current=null}
 async function inspect(e:FormEvent){e.preventDefault();setError('');setBusy(true);try{const total=cents(amount);const ids=payer==='split'||payer==='custom'?auth.members.map(p=>p.id):[payer];const body={description,buyer_id:buyer,card_id:card||null,purchased_at:date,total_cents:total,count,shares:ids.map((id,i)=>({user_id:id,weight:payer==='custom'?cents(custom[id]??'0'):Math.floor(total/ids.length)+(i<total%ids.length?1:0)})),...(!card?{first_month:firstMonth+'-01'}:{})};payload.current=body;setPreview(await api('/commitments/preview',{method:'POST',body:JSON.stringify(body)}))}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 async function save(){setBusy(true);setError('');try{pending.current??=createOperation('/commitments','POST',payload.current);await pending.current();onSaved()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 return <div className="dialog-backdrop"><section className="dialog" role="dialog" aria-modal="true" aria-labelledby="new-title"><header><div><span className="eyebrow">UM REGISTRO, TODOS OS MESES</span><h2 id="new-title">Adicionar gasto</h2></div><button aria-label="Fechar" onClick={onClose}><X size={18}/></button></header><form onSubmit={inspect} onChange={reset}><label>Descrição<input required maxLength={200} value={description} onChange={e=>setDescription(e.target.value)} placeholder="Ex.: mercado, celular, jantar…"/></label><div className="grid two"><label>Valor total (R$)<input required type="number" step="0.01" min="0.01" value={amount} onChange={e=>setAmount(e.target.value)} placeholder="0,00"/></label><label>Parcelas<input required type="number" min="1" max="120" value={count} onChange={e=>setCount(Number(e.target.value))}/></label><label>Data da compra<input required type="date" value={date} onChange={e=>setDate(e.target.value)}/></label><label>Forma de pagamento<select value={card} onChange={e=>setCard(e.target.value)}><option value="">Pix, boleto ou débito</option>{cards.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label>Quem comprou<select value={buyer} onChange={e=>setBuyer(e.target.value)}>{auth.members.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label>Quem fica responsável<select value={payer} onChange={e=>setPayer(e.target.value)}>{auth.members.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}<option value="split">Dividir igualmente</option><option value="custom">Dividir por valores</option></select></label>{!card&&<label>Primeira competência<input type="month" required value={firstMonth} onChange={e=>setFirstMonth(e.target.value)}/></label>}</div>{payer==='custom'&&<fieldset><legend>Valor de cada responsável</legend><div className="grid two">{auth.members.map(p=><label key={p.id}>Valor de {p.name} (R$)<input type="number" min="0" step="0.01" required value={custom[p.id]??''} onChange={e=>setCustom({...custom,[p.id]:e.target.value})}/></label>)}</div></fieldset>}<p className="form-help">{card?'A primeira fatura será calculada pelo fechamento do cartão.':'Escolha o mês em que o valor entra no planejamento.'}</p>{error&&<div className="error" role="alert">{error}</div>}{!preview&&<button className="primary" disabled={busy}>{busy?'Calculando…':'Conferir parcelas'}<ArrowRight size={16}/></button>}</form>{preview&&<><h3 style={{margin:'22px 0 12px'}}>Confira antes de salvar</h3><div className="preview-list">{preview.installments.map((p:any)=><div key={p.number}><span>{p.number}/{count} · {monthLabel(p.month.slice(0,7))}{p.needs_review?' · Conferir fatura':''}</span><strong>{money(p.amount_cents)}</strong></div>)}</div><footer><button onClick={reset}>Editar</button><button className="primary" disabled={busy} onClick={save}><Check size={17}/>{busy?'Salvando…':'Salvar gasto'}</button></footer></>}</section></div>
}
