import React from 'react'
import {cleanup,fireEvent,render,screen,waitFor} from '@testing-library/react'
import {afterEach,describe,expect,it,vi} from 'vitest'
import {api,createOperation} from '../api/client'
import {AddExpense} from './AddExpense'
import {ScheduledExpenseForm} from './ScheduledExpenseForm'
import {Cards} from '../pages/Cards'
vi.mock('../api/client',async()=>({...await vi.importActual('../api/client'),api:vi.fn(),createOperation:vi.fn()}))
const auth={user:{id:'u',name:'Douglas'},members:[{id:'u',name:'Douglas'}],family_id:'f'}
afterEach(()=>{cleanup();vi.clearAllMocks()})

describe('MODAL-01 standardized product dialogs',()=>{
 it('composes the expense chooser from the shared dialog with no legacy backdrop',()=>{render(<AddExpense auth={auth} month="2026-10" onClose={()=>{}} onSaved={()=>{}}/>);expect(screen.getByRole('dialog',{name:'Adicionar despesa'}).className).toBe('modal');expect(document.querySelector('.dialog-backdrop')).toBe(null)})
 it('keeps the purchase form in the same shared modal system',async()=>{vi.mocked(api).mockResolvedValue([]);render(<AddExpense auth={auth} month="2026-10" onClose={()=>{}} onSaved={()=>{}}/>);fireEvent.click(screen.getByRole('button',{name:/Compra ou despesa/}));expect(screen.getByRole('dialog',{name:'Compra ou despesa'})).toBeTruthy();expect(document.querySelector('.dialog-backdrop')).toBe(null)})
 it('renders recurring and import forms inside the primitive',()=>{vi.mocked(api).mockResolvedValue([]);render(<ScheduledExpenseForm auth={auth} mode="rule" initialMonth="2026-10" onClose={()=>{}} onBack={()=>{}} onSaved={()=>{}} feedback=""/>);expect(screen.getByRole('dialog',{name:'Conta recorrente'}).className).toBe('modal')})
 it('renders card creation inside the primitive',async()=>{vi.mocked(api).mockResolvedValue([]);render(<Cards auth={auth}/>);fireEvent.click(await screen.findByRole('button',{name:/Novo cartão/}));expect(screen.getByRole('dialog',{name:'Novo cartão'}).className).toBe('modal');expect(document.querySelector('.dialog-backdrop')).toBe(null)})
 it('collects invoice payment date without native browser prompts',async()=>{const card={id:'c',name:'Principal',institution:'Banco',holder_id:'u',closing_day:25,due_day:5};const cycle={id:'cy',version:2,month:'2026-10-01',closing_date:'2026-09-25',due_date:'2026-10-05',paid_at:null,confirmed:true};vi.mocked(api).mockImplementation(async path=>path==='/cards'?[card]:[cycle]);const prompt=vi.spyOn(window,'prompt');render(<Cards auth={auth}/>);fireEvent.click(await screen.findByRole('button',{name:'Ver faturas'}));fireEvent.click(await screen.findByRole('button',{name:'Pagar fatura'}));expect(screen.getByRole('dialog',{name:'Pagar fatura'})).toBeTruthy();expect(prompt).not.toHaveBeenCalled()})
 it('previews closing changes in a shared modal while preserving the selected date',async()=>{const card={id:'c',name:'Principal',institution:'Banco',holder_id:'u',closing_day:25,due_day:5};const cycle={id:'cy',version:2,month:'2026-10-01',closing_date:'2026-09-25',due_date:'2026-10-05',paid_at:null,confirmed:false};vi.mocked(api).mockImplementation(async(path)=>path==='/cards'?[card]:path.includes('preview-close')?{changes:[{commitment_id:'x',first_month:'2026-11-01'}]}:[cycle]);render(<Cards auth={auth}/>);fireEvent.click(await screen.findByRole('button',{name:'Ver faturas'}));fireEvent.click(await screen.findByRole('button',{name:'Ajustar fechamento'}));fireEvent.change(screen.getByLabelText('Fechamento efetivo'),{target:{value:'2026-09-20'}});fireEvent.click(screen.getByRole('button',{name:'Conferir fechamento'}));expect(await screen.findByText('1 compras terão a primeira competência alterada.')).toBeTruthy();expect(screen.getByRole('dialog',{name:'Conferir mudança de fechamento'})).toBeTruthy()})
 it.each([360,390,768,1440])('keeps modal bounds within the %ipx viewport without horizontal overflow',width=>{Object.defineProperty(window,'innerWidth',{configurable:true,value:width});render(<AddExpense auth={auth} month="2026-10" onClose={()=>{}} onSaved={()=>{}}/>);const dialog=screen.getByRole('dialog') as HTMLDialogElement;expect(dialog.style.width).toBe('calc(100% - 20px)');expect(dialog.style.maxWidth).toBe('640px');expect(dialog.style.maxHeight).toBe('calc(100dvh - 20px)')})
})
