import {useEffect,useState,type FormEvent} from 'react'
import {X} from 'lucide-react'
import type {Auth} from '../App'
import {api,createOperation,money,monthLabel} from '../api/client'
import {cents} from './CommitmentForm'
export function ScheduledExpenseForm({auth,mode,initialMonth,onClose,onBack,onSaved,feedback}:{auth:Auth,mode:'rule'|'import',initialMonth:string,onClose:()=>void,onBack:()=>void,onSaved:(again:boolean)=>void,feedback:string}){
 const [cards,setCards]=useState<any[]>([]),[form,setForm]=useState<any>({description:'',amount:'',start:initialMonth,day:5,user:auth.user.id,variable:false,count:12,numbers:'1-12',card:''}),[error,setError]=useState(''),[preview,setPreview]=useState<any>(null),[busy,setBusy]=useState(false)
 useEffect(()=>{api('/cards').then(setCards).catch(e=>setError(e.message))},[])
 function payload(){const shared=[{user_id:form.user,weight:1}];if(mode==='rule')return {description:form.description,amount_cents:cents(form.amount),variable:form.variable,due_day:Number(form.day),start_month:form.start+'-01',shares:shared};const numbers=form.numbers.split(',').flatMap((part:string)=>{const range=part.trim().split('-').map(Number);return range.length===1?range:Array.from({length:Math.max(0,Math.min(120,range[1]-range[0]+1))},(_,i)=>range[0]+i)});return {description:form.description,buyer_id:form.user,card_id:form.card||null,first_month:form.start+'-01',original_count:Number(form.count),numbers,installment_cents:cents(form.amount),due_day:Number(form.day),shares:shared}}
 async function submit(e:FormEvent){e.preventDefault();const again=(e.nativeEvent as SubmitEvent).submitter?.getAttribute('data-again')==='true';setError('');setBusy(true);try{if(mode==='import'&&!preview){setPreview(await api('/commitments/import-preview',{method:'POST',body:JSON.stringify(payload())}));return}await createOperation(mode==='rule'?'/recurrences':'/commitments/import','POST',payload())();onSaved(again)}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 return <div className="dialog-backdrop"><section className="dialog" role="dialog" aria-modal="true" aria-label={mode==='rule'?'Conta recorrente':'Parcelas em andamento'}><header><h2>{mode==='rule'?'Conta recorrente':'Parcelas em andamento'}</h2><button aria-label="Fechar" onClick={onClose}><X/></button></header><button type="button" className="link-button" onClick={onBack}>← Trocar tipo de despesa</button>{feedback&&<div role="status" className="notice">{feedback}</div>}<form onSubmit={submit} onChange={()=>setPreview(null)}><label>Descrição<input required value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></label><div className="grid two"><label>Valor da parcela ou conta (R$)<input type="number" step="0.01" min="0.01" required value={form.amount} onChange={e=>setForm({...form,amount:e.target.value})}/></label><label>Competência inicial<input type="month" required value={form.start} onChange={e=>setForm({...form,start:e.target.value})}/></label><label>Dia do vencimento<input type="number" min="1" max="31" required value={form.day} onChange={e=>setForm({...form,day:e.target.value})}/></label><label>Responsável<select value={form.user} onChange={e=>setForm({...form,user:e.target.value})}>{auth.members.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label></div>{mode==='rule'?<label className="checkbox-row"><input type="checkbox" checked={form.variable} onChange={e=>setForm({...form,variable:e.target.checked})}/>O valor muda todo mês (estimativa)</label>:<><div className="grid two"><label>Total original de parcelas<input required type="number" min="1" max="120" value={form.count} onChange={e=>setForm({...form,count:e.target.value})}/></label><label>Parcelas ainda abertas<input required value={form.numbers} onChange={e=>setForm({...form,numbers:e.target.value})} placeholder="10-44 ou 10,12-44"/></label></div><label>Cartão ou financiamento<select value={form.card} onChange={e=>setForm({...form,card:e.target.value})}><option value="">Financiamento / fora do cartão</option>{cards.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><p className="form-help">Ex.: contrato de 48 parcelas, ainda abertas de 10 a 44. Digite 48 e 10-44.</p></>}{error&&<div role="alert" className="error">{error}</div>}{preview&&<div className="preview-list">{preview.installments.map((p:any)=><div key={p.number}><span>{p.number}/{form.count} · {monthLabel(p.month.slice(0,7))}</span><strong>{money(p.amount_cents)}</strong></div>)}</div>}<div className="actions"><button className="primary" disabled={busy}>{mode==='rule'?'Salvar conta':preview?'Salvar parcelas':'Conferir parcelas restantes'}</button>{(mode==='rule'||preview)&&<button data-again="true" disabled={busy}>Salvar e adicionar outra</button>}</div></form></section></div>
}
