import {useEffect,useState,type FormEvent} from 'react'
import type {Auth} from '../App'
import {api,createOperation,money,monthLabel} from '../api/client'
import {cents} from './CommitmentForm'
import {Modal,ModalBody,ModalClose,ModalFooter,ModalFormError,ModalHeader} from './modal'

export function ScheduledExpenseForm({auth,mode,initialMonth,onClose,onBack,onSaved,feedback}:{auth:Auth;mode:'rule'|'import';initialMonth:string;onClose:()=>void;onBack:()=>void;onSaved:(again:boolean)=>void;feedback:string}){
 const [cards,setCards]=useState<any[]>([]),[form,setForm]=useState<any>({description:'',amount:'',start:initialMonth,day:5,user:auth.user.id,variable:false,count:12,numbers:'1-12',card:''}),[error,setError]=useState(''),[preview,setPreview]=useState<any>(null),[busy,setBusy]=useState(false)
 useEffect(()=>{api('/cards').then(setCards).catch(cause=>setError(cause.message))},[])
 function payload(){const shares=[{user_id:form.user,weight:1}];if(mode==='rule')return {description:form.description,amount_cents:cents(form.amount),variable:form.variable,due_day:Number(form.day),start_month:form.start+'-01',shares};const numbers=form.numbers.split(',').flatMap((part:string)=>{const range=part.trim().split('-').map(Number);return range.length===1?range:Array.from({length:Math.max(0,Math.min(120,range[1]-range[0]+1))},(_,index)=>range[0]+index)});return {description:form.description,buyer_id:form.user,card_id:form.card||null,first_month:form.start+'-01',original_count:Number(form.count),numbers,installment_cents:cents(form.amount),due_day:Number(form.day),shares}}
 async function submit(event:FormEvent){event.preventDefault();const again=(event.nativeEvent as SubmitEvent).submitter?.getAttribute('data-again')==='true';setError('');setBusy(true);try{if(mode==='import'&&!preview){setPreview(await api('/commitments/import-preview',{method:'POST',body:JSON.stringify(payload())}));return}await createOperation(mode==='rule'?'/recurrences':'/commitments/import','POST',payload())();onSaved(again)}catch(cause){setError((cause as Error).message)}finally{setBusy(false)}}
 return <Modal open onClose={onClose} busy={busy}><ModalHeader>{mode==='rule'?'Conta recorrente':'Parcelas em andamento'}</ModalHeader><ModalBody><button type="button" className="link-button" onClick={onBack}>← Trocar tipo de despesa</button>{feedback&&<div role="status" className="notice">{feedback}</div>}<form onSubmit={submit} onChange={()=>setPreview(null)}><label>Descrição<input required value={form.description} onChange={event=>setForm({...form,description:event.target.value})}/></label><div className="grid two"><label>Valor da parcela ou conta (R$)<input type="number" step="0.01" min="0.01" required value={form.amount} onChange={event=>setForm({...form,amount:event.target.value})}/></label><label>Competência inicial<input type="month" required value={form.start} onChange={event=>setForm({...form,start:event.target.value})}/></label><label>Dia do vencimento<input type="number" min="1" max="31" required value={form.day} onChange={event=>setForm({...form,day:event.target.value})}/></label><label>Responsável<select value={form.user} onChange={event=>setForm({...form,user:event.target.value})}>{auth.members.map(person=><option key={person.id} value={person.id}>{person.name}</option>)}</select></label></div>{mode==='rule'?<label className="checkbox-row"><input type="checkbox" checked={form.variable} onChange={event=>setForm({...form,variable:event.target.checked})}/>O valor muda todo mês (estimativa)</label>:<><div className="grid two"><label>Total original de parcelas<input required type="number" min="1" max="120" value={form.count} onChange={event=>setForm({...form,count:event.target.value})}/></label><label>Parcelas ainda abertas<input required value={form.numbers} onChange={event=>setForm({...form,numbers:event.target.value})} placeholder="10-44 ou 10,12-44"/></label></div><label>Cartão ou financiamento<select value={form.card} onChange={event=>setForm({...form,card:event.target.value})}><option value="">Financiamento / fora do cartão</option>{cards.map(card=><option key={card.id} value={card.id}>{card.name}</option>)}</select></label><p className="form-help">Ex.: contrato de 48 parcelas, ainda abertas de 10 a 44. Digite 48 e 10-44.</p></>}<ModalFormError message={error}/>{preview&&<div className="preview-list">{preview.installments.map((part:any)=><div key={part.number}><span>{part.number}/{form.count} · {monthLabel(part.month.slice(0,7))}</span><strong>{money(part.amount_cents)}</strong></div>)}</div>}<div className="actions"><button className="primary" disabled={busy}>{mode==='rule'?'Salvar conta':preview?'Salvar parcelas':'Conferir parcelas restantes'}</button>{(mode==='rule'||preview)&&<button data-again="true" disabled={busy}>Salvar e adicionar outra</button>}</div></form></ModalBody><ModalFooter><ModalClose>Fechar</ModalClose></ModalFooter></Modal>
}
