import React from 'react'
import {cleanup,fireEvent,render,screen,waitFor} from '@testing-library/react'
import {afterEach,describe,expect,it,vi} from 'vitest'
import {api,createOperation,ApiError} from '../../api/client'
import {EditCommitmentModal} from './EditCommitmentModal'
vi.mock('../../api/client',async()=>({...await vi.importActual('../../api/client'),api:vi.fn(),createOperation:vi.fn()}))

const members=[{id:'douglas',name:'Douglas'},{id:'vanessa',name:'Vanessa'}]
const cards=[{id:'card',name:'Principal'}]
const detail={id:'c1',version:4,description:'Mercado',category:'Casa',buyer_id:'douglas',card_id:null,purchased_at:'2026-09-12',total_cents:30000,original_count:3,shares:[{user_id:'douglas',weight:30000}],installments:[{id:'i1',number:1,month:'2026-10-01',amount_cents:10000,paid_at:null}]}
const preview={source_version:4,preview_hash:'b'.repeat(64),has_payments:false,allowed_fields:['description','category','buyer_id','card_id','purchased_at','total_cents','count','first_month','shares'],before:{commitment:{description:'Mercado'},installments:[{number:1,month:'2026-10-01',amount_cents:10000}]},after:{commitment:{description:'Supermercado'},installments:[{number:1,month:'2026-11-01',amount_cents:15000},{number:2,month:'2026-12-01',amount_cents:15000}]},affected_cycles:[{id:'cy',month:'2026-10-01',confirmed:true}],planned_advances:[{id:'a'}]}
function setup(data:any=detail,props:Partial<React.ComponentProps<typeof EditCommitmentModal>>={}){return render(<EditCommitmentModal open commitment={data} members={members} cards={cards} onClose={vi.fn()} onSaved={vi.fn()} {...props}/>) }
async function inspect(){fireEvent.click(screen.getByRole('button',{name:'Conferir alterações'}));await screen.findByText('Antes e depois')}
afterEach(()=>{cleanup();vi.clearAllMocks()})

describe('EDIT-02 edit commitment modal',()=>{
 it('prefills every editable field from the commitment',()=>{setup();expect((screen.getByLabelText('Descrição') as HTMLInputElement).value).toBe('Mercado');expect((screen.getByLabelText('Categoria') as HTMLInputElement).value).toBe('Casa');expect((screen.getByLabelText('Valor total (R$)') as HTMLInputElement).value).toBe('300.00');expect((screen.getByLabelText('Parcelas') as HTMLInputElement).value).toBe('3')})
 it('prefills buyer, payment method, purchase date and first competence',()=>{setup();expect((screen.getByLabelText('Quem comprou') as HTMLSelectElement).value).toBe('douglas');expect((screen.getByLabelText('Forma de pagamento') as HTMLSelectElement).value).toBe('');expect((screen.getByLabelText('Data da compra') as HTMLInputElement).value).toBe('2026-09-12');expect((screen.getByLabelText('Primeira competência') as HTMLInputElement).value).toBe('2026-10')})
 it('locks recalculation fields after a payment and explains why',()=>{setup({...detail,installments:[{...detail.installments[0],paid_at:'2026-10-10'}]});expect((screen.getByLabelText('Valor total (R$)') as HTMLInputElement).disabled).toBe(true);expect(screen.getByText(/Há pagamentos/)).toBeTruthy();expect((screen.getByLabelText('Descrição') as HTMLInputElement).disabled).toBe(false)})
 it('asks inside the product before discarding dirty values',()=>{const close=vi.fn();setup(detail,{onClose:close});fireEvent.change(screen.getByLabelText('Descrição'),{target:{value:'Mudou'}});fireEvent.click(screen.getByRole('button',{name:'Cancelar'}));expect(screen.getByText('Descartar alterações?')).toBeTruthy();expect(close).not.toHaveBeenCalled();fireEvent.click(screen.getByRole('button',{name:'Descartar alterações'}));expect(close).toHaveBeenCalledTimes(1)})
 it('sends all fields and shares to the preview contract',async()=>{vi.mocked(api).mockResolvedValue(preview);setup();await inspect();const body=JSON.parse(String(vi.mocked(api).mock.calls[0][1]?.body));expect(body).toMatchObject({version:4,description:'Mercado',category:'Casa',buyer_id:'douglas',total_cents:30000,count:3,first_month:'2026-10-01',shares:[{user_id:'douglas',weight:30000}]})})
 it('shows before and after schedules plus affected cycles and planned advances',async()=>{vi.mocked(api).mockResolvedValue(preview);setup();await inspect();expect(screen.getByText(/outubro de 2026/)).toBeTruthy();expect(screen.getByText(/novembro de 2026/)).toBeTruthy();expect(screen.getByText(/1 fatura/)).toBeTruthy();expect(screen.getByText(/1 antecipação planejada/)).toBeTruthy()})
 it('keeps field values and highlights fields returned by validation',async()=>{vi.mocked(api).mockRejectedValue(new ApiError('Revise os campos.',422,{fields:['description']}));setup();fireEvent.change(screen.getByLabelText('Descrição'),{target:{value:'Novo valor'}});fireEvent.click(screen.getByRole('button',{name:'Conferir alterações'}));expect(await screen.findByRole('alert')).toBeTruthy();expect((screen.getByLabelText('Descrição') as HTMLInputElement).value).toBe('Novo valor');expect(screen.getByLabelText('Descrição').getAttribute('aria-invalid')).toBe('true')})
 it('renders a server-provided partial-payment lock as an actionable error',async()=>{vi.mocked(api).mockRejectedValue(new ApiError('Há pagamentos. Altere somente descrição e categoria ou reabra-os.',409,{code:'paid_fields_locked',fields:['count']}));setup();fireEvent.click(screen.getByRole('button',{name:'Conferir alterações'}));expect((await screen.findByRole('alert')).textContent).toContain('reabra-os');expect(screen.getByText('Reabra os pagamentos no histórico para recalcular o contrato.')).toBeTruthy()})
 it('prevents duplicate confirmation while saving',async()=>{vi.mocked(api).mockResolvedValue(preview);let finish:(value:unknown)=>void=()=>{};vi.mocked(createOperation).mockReturnValue(vi.fn(()=>new Promise(resolve=>{finish=resolve})));setup();await inspect();fireEvent.click(screen.getByRole('button',{name:'Salvar alterações'}));expect((screen.getByRole('button',{name:'Salvando…'}) as HTMLButtonElement).disabled).toBe(true);finish({});await waitFor(()=>expect(createOperation).toHaveBeenCalledTimes(1))})
 it('confirms with the preview hash and notifies after success',async()=>{vi.mocked(api).mockResolvedValue(preview);vi.mocked(createOperation).mockReturnValue(vi.fn().mockResolvedValue({}));const saved=vi.fn();setup(detail,{onSaved:saved});await inspect();fireEvent.click(screen.getByRole('button',{name:'Salvar alterações'}));await waitFor(()=>expect(saved).toHaveBeenCalledTimes(1));expect(createOperation).toHaveBeenCalledWith('/commitments/c1','PATCH',expect.objectContaining({version:4,preview_hash:'b'.repeat(64)}))})
})
