import React from 'react'
import {cleanup,fireEvent,render,screen,waitFor} from '@testing-library/react'
import {afterEach,describe,expect,it,vi} from 'vitest'
import {TransferResponsibilityModal} from './TransferResponsibilityModal'
import {ApiError,api,createOperation} from '../../api/client'

vi.mock('../../api/client',async()=>({...await vi.importActual('../../api/client'),api:vi.fn(),createOperation:vi.fn()}))
const members=[{id:'douglas',name:'Douglas'},{id:'vanessa',name:'Vanessa'}]
const preview={source_version:3,preview_hash:'a'.repeat(64),open_total_cents:20000,open_installment_count:2,months:['2026-10','2026-11'],planned_advances:[{id:'advance',month:'2026-09-01',amount_cents:18000,installment_ids:['i1','i2']}],installments:[{id:'i1',number:3,month:'2026-10-01',amount_cents:10000,before:[{user_id:'douglas',weight:10000}],after:[{user_id:'vanessa',weight:10000}]}]}

function setup(props:Partial<React.ComponentProps<typeof TransferResponsibilityModal>>={}){
 return render(<TransferResponsibilityModal open commitmentId="c1" version={3} openTotalCents={20000} currentShares={[{user_id:'douglas',weight:20000}]} members={members} onClose={vi.fn()} onSaved={vi.fn()} {...props}/>)
}
async function makePreview(){fireEvent.click(screen.getByRole('button',{name:'Conferir transferência'}));await screen.findByText('2 parcelas abertas')}

afterEach(()=>{cleanup();vi.clearAllMocks()})

describe('EDIT-01 transfer modal',()=>{
 it('shows the current responsible person and defaults the destination to the other member',()=>{setup();expect(screen.getByText('Douglas')).toBeTruthy();expect((screen.getByLabelText('Transferir 100% para') as HTMLSelectElement).value).toBe('vanessa')})
 it('previews the affected count, months and planned advances',async()=>{vi.mocked(api).mockResolvedValue(preview);setup();await makePreview();expect(screen.getByText(/outubro de 2026/)).toBeTruthy();expect(screen.getByText(/novembro de 2026/)).toBeTruthy();expect(screen.getByText(/1 antecipação planejada/)).toBeTruthy()})
 it('sends a 100% destination share for the full open total',async()=>{vi.mocked(api).mockResolvedValue(preview);setup();await makePreview();expect(vi.mocked(api).mock.calls[0][1]).toMatchObject({method:'POST',body:JSON.stringify({version:3,shares:[{user_id:'vanessa',weight:20000}]})})})
 it('supports an advanced split whose values sum exactly to the open obligation',async()=>{vi.mocked(api).mockResolvedValue(preview);setup();fireEvent.click(screen.getByRole('button',{name:'Editar divisão'}));fireEvent.change(screen.getByLabelText('Valor de Douglas (R$)'),{target:{value:'50'}});fireEvent.change(screen.getByLabelText('Valor de Vanessa (R$)'),{target:{value:'150'}});fireEvent.click(screen.getByRole('button',{name:'Conferir transferência'}));await waitFor(()=>expect(vi.mocked(api)).toHaveBeenCalled());expect(JSON.parse(String(vi.mocked(api).mock.calls[0][1]?.body)).shares).toEqual([{user_id:'douglas',weight:5000},{user_id:'vanessa',weight:15000}])})
 it('rejects a split that does not close and explains the difference without calling the API',()=>{setup();fireEvent.click(screen.getByRole('button',{name:'Editar divisão'}));fireEvent.change(screen.getByLabelText('Valor de Douglas (R$)'),{target:{value:'50'}});fireEvent.change(screen.getByLabelText('Valor de Vanessa (R$)'),{target:{value:'100'}});fireEvent.click(screen.getByRole('button',{name:'Conferir transferência'}));expect(screen.getByRole('alert').textContent).toContain('Faltam R$ 50,00');expect(api).not.toHaveBeenCalled()})
 it('keeps advanced values after a structured validation error',async()=>{vi.mocked(api).mockRejectedValue(new ApiError('A divisão deve somar exatamente o total aberto.',422,{code:'invalid_split',fields:['shares'],difference_cents:100}));setup();fireEvent.click(screen.getByRole('button',{name:'Editar divisão'}));fireEvent.change(screen.getByLabelText('Valor de Douglas (R$)'),{target:{value:'50'}});fireEvent.change(screen.getByLabelText('Valor de Vanessa (R$)'),{target:{value:'150'}});fireEvent.click(screen.getByRole('button',{name:'Conferir transferência'}));expect((await screen.findByRole('alert')).textContent).toContain('A divisão deve');expect((screen.getByLabelText('Valor de Douglas (R$)') as HTMLInputElement).value).toBe('50')})
 it('keeps inputs and asks for a refreshed preview after a stale confirmation',async()=>{vi.mocked(api).mockResolvedValue(preview);const apply=vi.fn().mockRejectedValue(new ApiError('A prévia não representa mais as parcelas abertas. Recarregue.',409,{code:'version_conflict'}));vi.mocked(createOperation).mockReturnValue(apply);setup();await makePreview();fireEvent.click(screen.getByRole('button',{name:'Confirmar transferência'}));expect((await screen.findByRole('alert')).textContent).toContain('Recarregue');expect(screen.getByRole('button',{name:'Recarregar prévia'})).toBeTruthy();expect((screen.getByLabelText('Transferir 100% para') as HTMLSelectElement).value).toBe('vanessa')})
 it('disables duplicate actions while confirmation is running and calls onSaved once',async()=>{vi.mocked(api).mockResolvedValue(preview);let finish:(value:unknown)=>void=()=>{};const apply=vi.fn(()=>new Promise(resolve=>{finish=resolve}));vi.mocked(createOperation).mockReturnValue(apply);const saved=vi.fn();setup({onSaved:saved});await makePreview();fireEvent.click(screen.getByRole('button',{name:'Confirmar transferência'}));expect((screen.getByRole('button',{name:'Transferindo…'}) as HTMLButtonElement).disabled).toBe(true);finish({});await waitFor(()=>expect(saved).toHaveBeenCalledTimes(1))})
})
