import React from 'react'
import {cleanup,fireEvent,render,screen,waitFor} from '@testing-library/react'
import {afterEach,describe,expect,it,vi} from 'vitest'
import {FamilyInviteModal} from './FamilyInviteModal'
import {InviteLanding} from '../../pages/InviteLanding'
import {api} from '../../api/client'

vi.mock('../../api/client',async()=>({...await vi.importActual('../../api/client'),api:vi.fn()}))
const invite={id:'invite',link:'http://localhost:5173/invite?token=family.secret',expires_at:'2026-09-20T10:00:00Z',one_time:true}
afterEach(()=>{cleanup();vi.clearAllMocks();vi.unstubAllGlobals();window.history.replaceState({},'', '/')})

describe('INVITE-01 sharing',()=>{
 it('uses the native Web Share API with family name and link',async()=>{const share=vi.fn().mockResolvedValue(undefined);vi.stubGlobal('navigator',{...navigator,share,clipboard:{writeText:vi.fn()}});render(<FamilyInviteModal open invite={invite} familyName="Família Silva" onClose={()=>{}}/>);fireEvent.click(screen.getByRole('button',{name:'Compartilhar'}));await waitFor(()=>expect(share).toHaveBeenCalledWith(expect.objectContaining({text:expect.stringContaining('Família Silva'),url:invite.link})))})
 it('opens WhatsApp only after the explicit user action',()=>{const open=vi.spyOn(window,'open').mockImplementation(()=>null);render(<FamilyInviteModal open invite={invite} familyName="Família Silva" onClose={()=>{}}/>);expect(open).not.toHaveBeenCalled();fireEvent.click(screen.getByRole('button',{name:'Enviar pelo WhatsApp'}));expect(open).toHaveBeenCalledWith(expect.stringMatching(/^https:\/\/wa\.me\/\?text=/),'_blank','noopener,noreferrer')})
 it('copies the link as an always available fallback',async()=>{const writeText=vi.fn().mockResolvedValue(undefined);vi.stubGlobal('navigator',{...navigator,clipboard:{writeText}});render(<FamilyInviteModal open invite={invite} familyName="Família Silva" onClose={()=>{}}/>);fireEvent.click(screen.getByRole('button',{name:'Copiar link'}));await waitFor(()=>expect(writeText).toHaveBeenCalledWith(invite.link));expect(screen.getByRole('status').textContent).toContain('copiado')})
 it('warns that localhost links work only in the same environment',()=>{render(<FamilyInviteModal open invite={invite} familyName="Família Silva" onClose={()=>{}}/>);expect(screen.getByText(/mesmo dispositivo\/ambiente/)).toBeTruthy()})
 it('does not pretend a replayed response still contains a shareable token',()=>{render(<FamilyInviteModal open invite={{...invite,link:null,one_time:false}} familyName="Família Silva" onClose={()=>{}}/>);expect(screen.getByText(/novo convite para compartilhar/)).toBeTruthy();expect(screen.queryByRole('button',{name:'Copiar link'})).toBeNull()})
})

describe('INVITE-01 landing',()=>{
 it('removes token from URL before sending POST inspection',async()=>{window.history.replaceState({},'', '/invite?token=family.secret');vi.mocked(api).mockImplementation(async(path)=>{expect(window.location.search).toBe('');expect(path).toBe('/auth/invites/inspect');return {status:'valid',family_name:'Família Silva',expires_at:'2026-09-20T10:00:00Z'} as never});render(<InviteLanding/>);expect(await screen.findByText('Família Silva')).toBeTruthy();expect(window.location.pathname).toBe('/invite')})
 it('never renders the raw token in the document',async()=>{window.history.replaceState({},'', '/invite?token=family.super-secret');vi.mocked(api).mockResolvedValue({status:'valid',family_name:'Casa',expires_at:'2026-09-20T10:00:00Z'});render(<InviteLanding/>);await screen.findByText('Casa');expect(document.body.textContent).not.toContain('super-secret')})
 it('offers existing-account login and accepts after authentication',async()=>{window.history.replaceState({},'', '/invite?token=family.secret');vi.mocked(api).mockResolvedValueOnce({status:'valid',family_name:'Casa',expires_at:'x'}).mockResolvedValueOnce({csrf_token:'csrf',user:{id:'u',name:'Douglas'}}).mockResolvedValueOnce({status:'accepted',family_id:'family'});const done=vi.fn();render(<InviteLanding onComplete={done}/>);await screen.findByText('Casa');fireEvent.change(screen.getByLabelText('Email'),{target:{value:'douglas@test.local'}});fireEvent.change(screen.getByLabelText('Senha'),{target:{value:'testing-password'}});fireEvent.click(screen.getByRole('button',{name:'Entrar e aceitar convite'}));await waitFor(()=>expect(api).toHaveBeenNthCalledWith(2,'/auth/login',expect.objectContaining({method:'POST'})));expect(api).toHaveBeenNthCalledWith(3,'/auth/invites/accept',expect.objectContaining({method:'POST'}));expect(done).toHaveBeenCalled()})
 it('registers a new account through the invitation only',async()=>{window.history.replaceState({},'', '/invite?token=family.secret');vi.mocked(api).mockResolvedValueOnce({status:'valid',family_name:'Casa',expires_at:'x'}).mockResolvedValueOnce({user:{id:'u',name:'Nova'},family_id:'family'});render(<InviteLanding onComplete={()=>{}}/>);await screen.findByText('Casa');fireEvent.click(screen.getByRole('button',{name:'Criar conta'}));fireEvent.change(screen.getByLabelText('Nome'),{target:{value:'Nova'}});fireEvent.change(screen.getByLabelText('Email'),{target:{value:'nova@test.local'}});fireEvent.change(screen.getByLabelText('Senha'),{target:{value:'senha bastante longa'}});fireEvent.click(screen.getByRole('button',{name:'Criar conta e entrar'}));await waitFor(()=>expect(api).toHaveBeenLastCalledWith('/auth/invites/register',expect.objectContaining({method:'POST',body:expect.stringContaining('family.secret')})))})
 it('shows invalid, expired, revoked and used responses without internal detail',async()=>{window.history.replaceState({},'', '/invite?token=family.secret');vi.mocked(api).mockRejectedValue(new Error('Este convite expirou ou não está mais disponível. Peça um novo convite.'));render(<InviteLanding/>);expect((await screen.findByRole('alert')).textContent).toContain('Peça um novo convite')})
 it('explains when the URL has no invitation token',async()=>{window.history.replaceState({},'', '/invite');render(<InviteLanding/>);expect(await screen.findByText(/Link de convite incompleto/)).toBeTruthy();expect(api).not.toHaveBeenCalled()})
 it('preserves form values when login or registration fails',async()=>{window.history.replaceState({},'', '/invite?token=family.secret');vi.mocked(api).mockResolvedValueOnce({status:'valid',family_name:'Casa',expires_at:'x'}).mockRejectedValueOnce(new Error('Email ou senha incorretos.'));render(<InviteLanding/>);await screen.findByText('Casa');fireEvent.change(screen.getByLabelText('Email'),{target:{value:'douglas@test.local'}});fireEvent.change(screen.getByLabelText('Senha'),{target:{value:'wrong'}});fireEvent.click(screen.getByRole('button',{name:'Entrar e aceitar convite'}));expect((await screen.findByRole('alert')).textContent).toContain('Email ou senha incorretos');expect((screen.getByLabelText('Email') as HTMLInputElement).value).toBe('douglas@test.local')})
})
