"""initial relational schema

Revision ID: 84e008d3ef75
Revises: 
Create Date: 2026-09-10 09:12:18.759886

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '84e008d3ef75'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('families',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('login_attempt_windows',
    sa.Column('origin', sa.String(length=64), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('origin')
    )
    op.create_table('users',
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('audit_events',
    sa.Column('actor_id', sa.String(length=36), nullable=False),
    sa.Column('operation', sa.String(length=200), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=True),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('family_id', sa.String(length=36), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_events_family_id'), 'audit_events', ['family_id'], unique=False)
    op.create_table('idempotency_records',
    sa.Column('key', sa.String(length=200), nullable=False),
    sa.Column('payload_hash', sa.String(length=64), nullable=False),
    sa.Column('result', sa.JSON(), nullable=False),
    sa.Column('family_id', sa.String(length=36), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('family_id', 'key')
    )
    op.create_index(op.f('ix_idempotency_records_family_id'), 'idempotency_records', ['family_id'], unique=False)
    op.create_table('memberships',
    sa.Column('family_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('family_id', 'user_id')
    )
    op.create_table('month_closures',
    sa.Column('month', sa.Date(), nullable=False),
    sa.Column('closed', sa.Boolean(), nullable=False),
    sa.Column('family_id', sa.String(length=36), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('family_id', 'month')
    )
    op.create_index(op.f('ix_month_closures_family_id'), 'month_closures', ['family_id'], unique=False)
    op.create_table('recurring_rules',
    sa.Column('description', sa.String(length=200), nullable=False),
    sa.Column('start_month', sa.Date(), nullable=False),
    sa.Column('end_month', sa.Date(), nullable=True),
    sa.Column('amount_cents', sa.BigInteger(), nullable=False),
    sa.Column('variable', sa.Boolean(), nullable=False),
    sa.Column('due_day', sa.Integer(), nullable=False),
    sa.Column('shares', sa.JSON(), nullable=False),
    sa.Column('family_id', sa.String(length=36), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.CheckConstraint('amount_cents > 0 AND due_day BETWEEN 1 AND 31'),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id', 'family_id')
    )
    op.create_index(op.f('ix_recurring_rules_family_id'), 'recurring_rules', ['family_id'], unique=False)
    op.create_table('sessions',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('csrf_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index(op.f('ix_sessions_user_id'), 'sessions', ['user_id'], unique=False)
    op.create_table('cards',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('institution', sa.String(length=200), nullable=False),
    sa.Column('holder_id', sa.String(length=36), nullable=False),
    sa.Column('closing_day', sa.Integer(), nullable=False),
    sa.Column('due_day', sa.Integer(), nullable=False),
    sa.Column('family_id', sa.String(length=36), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.CheckConstraint('closing_day BETWEEN 1 AND 31 AND due_day BETWEEN 1 AND 31'),
    sa.ForeignKeyConstraint(['family_id', 'holder_id'], ['memberships.family_id', 'memberships.user_id'], ),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id', 'family_id')
    )
    op.create_index(op.f('ix_cards_family_id'), 'cards', ['family_id'], unique=False)
    op.create_table('recurring_occurrences',
    sa.Column('recurrence_id', sa.String(length=36), nullable=False),
    sa.Column('month', sa.Date(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('amount_cents', sa.BigInteger(), nullable=False),
    sa.Column('estimated', sa.Boolean(), nullable=False),
    sa.Column('paid_at', sa.Date(), nullable=True),
    sa.Column('family_id', sa.String(length=36), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.CheckConstraint('amount_cents > 0'),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], ),
    sa.ForeignKeyConstraint(['recurrence_id', 'family_id'], ['recurring_rules.id', 'recurring_rules.family_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('recurrence_id', 'month')
    )
    op.create_index(op.f('ix_recurring_occurrences_family_id'), 'recurring_occurrences', ['family_id'], unique=False)
    op.create_index(op.f('ix_recurring_occurrences_month'), 'recurring_occurrences', ['month'], unique=False)
    op.create_table('commitments',
    sa.Column('description', sa.String(length=200), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('buyer_id', sa.String(length=36), nullable=False),
    sa.Column('card_id', sa.String(length=36), nullable=True),
    sa.Column('purchased_at', sa.Date(), nullable=False),
    sa.Column('total_cents', sa.BigInteger(), nullable=False),
    sa.Column('original_count', sa.Integer(), nullable=False),
    sa.Column('imported', sa.Boolean(), nullable=False),
    sa.Column('family_id', sa.String(length=36), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.CheckConstraint('original_count BETWEEN 1 AND 120 AND total_cents > 0'),
    sa.ForeignKeyConstraint(['card_id', 'family_id'], ['cards.id', 'cards.family_id'], ),
    sa.ForeignKeyConstraint(['family_id', 'buyer_id'], ['memberships.family_id', 'memberships.user_id'], ),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id', 'family_id')
    )
    op.create_index(op.f('ix_commitments_family_id'), 'commitments', ['family_id'], unique=False)
    op.create_table('invoice_cycles',
    sa.Column('card_id', sa.String(length=36), nullable=False),
    sa.Column('month', sa.Date(), nullable=False),
    sa.Column('closing_date', sa.Date(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('confirmed', sa.Boolean(), nullable=False),
    sa.Column('paid_at', sa.Date(), nullable=True),
    sa.Column('family_id', sa.String(length=36), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.CheckConstraint('due_date > closing_date'),
    sa.ForeignKeyConstraint(['card_id', 'family_id'], ['cards.id', 'cards.family_id'], ),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('card_id', 'month'),
    sa.UniqueConstraint('id', 'family_id')
    )
    op.create_index(op.f('ix_invoice_cycles_family_id'), 'invoice_cycles', ['family_id'], unique=False)
    op.create_table('advance_plans',
    sa.Column('commitment_id', sa.String(length=36), nullable=False),
    sa.Column('month', sa.Date(), nullable=False),
    sa.Column('planned_date', sa.Date(), nullable=False),
    sa.Column('amount_cents', sa.BigInteger(), nullable=False),
    sa.Column('state', sa.String(length=20), nullable=False),
    sa.Column('family_id', sa.String(length=36), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.CheckConstraint("state IN ('planned', 'paid', 'cancelled') AND amount_cents > 0"),
    sa.ForeignKeyConstraint(['commitment_id', 'family_id'], ['commitments.id', 'commitments.family_id'], ),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id', 'family_id')
    )
    op.create_index(op.f('ix_advance_plans_family_id'), 'advance_plans', ['family_id'], unique=False)
    op.create_table('installments',
    sa.Column('commitment_id', sa.String(length=36), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('original_cents', sa.BigInteger(), nullable=False),
    sa.Column('amount_cents', sa.BigInteger(), nullable=False),
    sa.Column('original_month', sa.Date(), nullable=False),
    sa.Column('month', sa.Date(), nullable=False),
    sa.Column('original_due', sa.Date(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('original_cycle_id', sa.String(length=36), nullable=True),
    sa.Column('cycle_id', sa.String(length=36), nullable=True),
    sa.Column('paid_at', sa.Date(), nullable=True),
    sa.Column('payment_kind', sa.String(length=20), nullable=True),
    sa.Column('needs_review', sa.Boolean(), nullable=False),
    sa.Column('manually_assigned', sa.Boolean(), nullable=False),
    sa.Column('family_id', sa.String(length=36), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.CheckConstraint('number > 0 AND original_cents > 0 AND amount_cents > 0'),
    sa.ForeignKeyConstraint(['commitment_id', 'family_id'], ['commitments.id', 'commitments.family_id'], ),
    sa.ForeignKeyConstraint(['cycle_id', 'family_id'], ['invoice_cycles.id', 'invoice_cycles.family_id'], ),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], ),
    sa.ForeignKeyConstraint(['original_cycle_id', 'family_id'], ['invoice_cycles.id', 'invoice_cycles.family_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('commitment_id', 'number'),
    sa.UniqueConstraint('id', 'family_id')
    )
    op.create_index(op.f('ix_installments_cycle_id'), 'installments', ['cycle_id'], unique=False)
    op.create_index(op.f('ix_installments_family_id'), 'installments', ['family_id'], unique=False)
    op.create_index(op.f('ix_installments_month'), 'installments', ['month'], unique=False)
    op.create_table('responsibility_shares',
    sa.Column('commitment_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('weight', sa.BigInteger(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('family_id', sa.String(length=36), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.CheckConstraint('weight >= 0'),
    sa.ForeignKeyConstraint(['commitment_id', 'family_id'], ['commitments.id', 'commitments.family_id'], ),
    sa.ForeignKeyConstraint(['family_id', 'user_id'], ['memberships.family_id', 'memberships.user_id'], ),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('commitment_id', 'user_id')
    )
    op.create_index(op.f('ix_responsibility_shares_family_id'), 'responsibility_shares', ['family_id'], unique=False)
    op.create_table('advance_items',
    sa.Column('advance_id', sa.String(length=36), nullable=False),
    sa.Column('installment_id', sa.String(length=36), nullable=False),
    sa.Column('snapshot', sa.JSON(), nullable=False),
    sa.Column('family_id', sa.String(length=36), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['advance_id', 'family_id'], ['advance_plans.id', 'advance_plans.family_id'], ),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], ),
    sa.ForeignKeyConstraint(['installment_id', 'family_id'], ['installments.id', 'installments.family_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('advance_id', 'installment_id')
    )
    op.create_index(op.f('ix_advance_items_family_id'), 'advance_items', ['family_id'], unique=False)
    # ### end Alembic commands ###


    op.execute("DO $$ BEGIN IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname='expense_app') THEN CREATE ROLE expense_app NOLOGIN; END IF; END $$")
    op.execute("GRANT USAGE ON SCHEMA public TO expense_app")
    op.execute("GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO expense_app")
    for table in ('cards','invoice_cycles','commitments','responsibility_shares','installments','recurring_rules','recurring_occurrences','advance_plans','advance_items','month_closures','idempotency_records','audit_events'):
        op.execute(f'ALTER TABLE {table} ENABLE ROW LEVEL SECURITY')
        op.execute(f'ALTER TABLE {table} FORCE ROW LEVEL SECURITY')
        op.execute(f"CREATE POLICY family_isolation ON {table} USING (family_id = current_setting('app.family_id', true)) WITH CHECK (family_id = current_setting('app.family_id', true))")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_advance_items_family_id'), table_name='advance_items')
    op.drop_table('advance_items')
    op.drop_index(op.f('ix_responsibility_shares_family_id'), table_name='responsibility_shares')
    op.drop_table('responsibility_shares')
    op.drop_index(op.f('ix_installments_month'), table_name='installments')
    op.drop_index(op.f('ix_installments_family_id'), table_name='installments')
    op.drop_index(op.f('ix_installments_cycle_id'), table_name='installments')
    op.drop_table('installments')
    op.drop_index(op.f('ix_advance_plans_family_id'), table_name='advance_plans')
    op.drop_table('advance_plans')
    op.drop_index(op.f('ix_invoice_cycles_family_id'), table_name='invoice_cycles')
    op.drop_table('invoice_cycles')
    op.drop_index(op.f('ix_commitments_family_id'), table_name='commitments')
    op.drop_table('commitments')
    op.drop_index(op.f('ix_recurring_occurrences_month'), table_name='recurring_occurrences')
    op.drop_index(op.f('ix_recurring_occurrences_family_id'), table_name='recurring_occurrences')
    op.drop_table('recurring_occurrences')
    op.drop_index(op.f('ix_cards_family_id'), table_name='cards')
    op.drop_table('cards')
    op.drop_index(op.f('ix_sessions_user_id'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_index(op.f('ix_recurring_rules_family_id'), table_name='recurring_rules')
    op.drop_table('recurring_rules')
    op.drop_index(op.f('ix_month_closures_family_id'), table_name='month_closures')
    op.drop_table('month_closures')
    op.drop_table('memberships')
    op.drop_index(op.f('ix_idempotency_records_family_id'), table_name='idempotency_records')
    op.drop_table('idempotency_records')
    op.drop_index(op.f('ix_audit_events_family_id'), table_name='audit_events')
    op.drop_table('audit_events')
    op.drop_table('users')
    op.drop_table('login_attempt_windows')
    op.drop_table('families')
    # ### end Alembic commands ###
