import {useEffect,useState,type FormEvent} from 'react'
import {CreditCard,Plus,X,Pencil} from 'lucide-react'
import type {Auth} from '../App'
import {api,createOperation,monthLabel,today} from '../api/client'
export function Cards({auth}:{auth:Auth}){
 const [cards,setCards]=useState<any[]>([]),[cycles,setCycles]=useState<any[]>([]),[selected,setSelected]=useState<any>(null),[form,setForm]=useState<any>(null),[error,setError]=useState(''),[closePreview,setClosePreview]=useState<any>(null)
 const load=()=>api('/cards').then(setCards).catch(e=>setError(e.message))
 useEffect(()=>{load()},[])
 async function select(card:any){setSelected(card);setCycles(await api(`/cards/${card.id}/cycles`))}
 async function save(e:FormEvent){e.preventDefault();try{await createOperation(form.id?`/cards/${form.id}`:'/cards',form.id?'PATCH':'POST',form)();setForm(null);await load()}catch(e){setError((e as Error).message)}}
 async function cycleAction(c:any,action:string){try{const data:any={version:c.version};if(action==='pay'){const value=window.prompt('Data do pagamento (AAAA-MM-DD)',today());if(!value)return;data.paid_at=value}await createOperation(`/${action==='confirm'?'cycles':'invoices'}/${c.id}/${action}`,'POST',data)();await select(selected)}catch(e){setError((e as Error).message)}}
 async function preview(c:any){const closing=window.prompt('Fechamento efetivo (AAAA-MM-DD)',c.closing_date);if(!closing)return;try{const body={version:c.version,closing_date:closing};const result=await api(`/cycles/${c.id}/preview-close`,{method:'POST',body:JSON.stringify(body)});setClosePreview({cycle:c,body,result})}catch(e){setError((e as Error).message)}}
 return <>{error&&<div className="error" role="alert">{error}</div>}<div className="row spread section-title"><p>O cartão pode ser de um. A compra fica com quem é responsável.</p><button onClick={()=>{setError('');setForm({name:'',institution:'',holder_id:auth.user.id,closing_day:25,due_day:5})}}><Plus size={17}/>Novo cartão</button></div><div className="grid two">{cards.map((c,i)=><article className="panel" key={c.id} style={{background:i%2?'#e9eee0':'#244e41',color:i%2?'#35513c':'white'}}><div className="row spread"><CreditCard/><span style={{fontSize:11}}>{c.institution}</span><button aria-label={`Editar ${c.name}`} onClick={()=>setForm(c)}><Pencil size={14}/></button></div><h2 style={{margin:'28px 0 6px'}}>{c.name}</h2><small style={{color:'inherit',opacity:.7}}>{auth.members.find(p=>p.id===c.holder_id)?.name}</small><div className="row spread" style={{marginTop:25,fontSize:12}}><span>Fecha dia <strong>{c.closing_day}</strong></span><span>Vence dia <strong>{c.due_day}</strong></span><button onClick={()=>select(c)}>Ver faturas</button></div></article>)}</div>{!cards.length&&<div className="panel empty">Cadastre seu primeiro cartão para calcular as faturas automaticamente.</div>}
 {selected&&<section className="panel" style={{marginTop:24}}><h3>Faturas · {selected.name}</h3>{!cycles.length&&<p>As faturas aparecerão quando você registrar uma compra neste cartão.</p>}{cycles.map(c=><div className="row spread" key={c.id} style={{padding:'18px 0',borderBottom:'1px solid var(--line)'}}><div><strong>{monthLabel(c.month.slice(0,7))}</strong><span className="subtext">Fechamento {c.closing_date} · Vencimento {c.due_date}</span><span className={'badge '+(c.paid_at?'':'amber')}>{c.paid_at?'Paga':c.confirmed?'Conferida':'A conferir'}</span></div><div className="actions"><button onClick={()=>preview(c)}>Ajustar fechamento</button><button onClick={()=>cycleAction(c,'confirm')}>Conferir</button><button onClick={()=>cycleAction(c,c.paid_at?'reopen':'pay')}>{c.paid_at?'Reabrir':'Pagar fatura'}</button></div></div>)}</section>}
 {form&&<div className="dialog-backdrop"><section className="dialog" role="dialog" aria-modal="true" aria-label="Cadastro do cartão"><header><h2>{form.id?'Editar cartão':'Novo cartão'}</h2><button aria-label="Fechar" onClick={()=>setForm(null)}><X/></button></header><form onSubmit={save}><label>Nome do cartão<input required maxLength={200} value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><label>Instituição<input required maxLength={200} value={form.institution} onChange={e=>setForm({...form,institution:e.target.value})}/></label><label>Titular<select value={form.holder_id} onChange={e=>setForm({...form,holder_id:e.target.value})}>{auth.members.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><div className="grid two"><label>Dia do fechamento<input required type="number" min="1" max="31" value={form.closing_day} onChange={e=>setForm({...form,closing_day:Number(e.target.value)})}/></label><label>Dia do vencimento<input required type="number" min="1" max="31" value={form.due_day} onChange={e=>setForm({...form,due_day:Number(e.target.value)})}/></label></div>{error&&<div role="alert" className="error">{error}</div>}<button className="primary">Salvar cartão</button></form></section></div>}
 {closePreview&&<div className="dialog-backdrop"><section className="dialog" role="dialog" aria-label="Conferir fechamento"><h2>Conferir mudança de fechamento</h2><p>{closePreview.result.changes.length} compras terão a primeira competência alterada.</p><div className="preview-list">{closePreview.result.changes.map((c:any)=><div key={c.commitment_id}><span>Compra vinculada</span><strong>{monthLabel(c.first_month.slice(0,7))}</strong></div>)}</div><footer><button onClick={()=>setClosePreview(null)}>Cancelar</button><button className="primary" onClick={async()=>{try{await createOperation(`/cycles/${closePreview.cycle.id}/close`,'PATCH',closePreview.body)();setClosePreview(null);await select(selected)}catch(e){setError((e as Error).message)}}}>Aplicar alteração</button></footer></section></div>}
 </>
}
