import {useEffect,useState,type FormEvent} from 'react'
import {CreditCard,Plus,Pencil} from 'lucide-react'
import type {Auth} from '../App'
import {api,createOperation,monthLabel,today} from '../api/client'
import {Modal,ModalBody,ModalFooter,ModalFormError,ModalHeader} from '../components/modal'

export function Cards({auth}:{auth:Auth}){
 const [cards,setCards]=useState<any[]>([]),[cycles,setCycles]=useState<any[]>([]),[selected,setSelected]=useState<any>(null),[form,setForm]=useState<any>(null),[error,setError]=useState(''),[cycleDialog,setCycleDialog]=useState<any>(null),[busy,setBusy]=useState(false)
 const load=()=>api('/cards').then(setCards).catch(cause=>setError(cause.message))
 useEffect(()=>{load()},[])
 async function select(card:any){setSelected(card);setCycles(await api(`/cards/${card.id}/cycles`))}
 async function save(event:FormEvent){event.preventDefault();setBusy(true);try{await createOperation(form.id?`/cards/${form.id}`:'/cards',form.id?'PATCH':'POST',form)();setForm(null);await load()}catch(cause){setError((cause as Error).message)}finally{setBusy(false)}}
 async function cycleAction(cycle:any,action:string){if(action==='pay'){setCycleDialog({kind:'pay',cycle,value:today(),error:''});return}setBusy(true);try{await createOperation(`/${action==='confirm'?'cycles':'invoices'}/${cycle.id}/${action}`,'POST',{version:cycle.version})();await select(selected)}catch(cause){setError((cause as Error).message)}finally{setBusy(false)}}
 async function payInvoice(){setBusy(true);try{await createOperation(`/invoices/${cycleDialog.cycle.id}/pay`,'POST',{version:cycleDialog.cycle.version,paid_at:cycleDialog.value})();setCycleDialog(null);await select(selected)}catch(cause){setCycleDialog({...cycleDialog,error:(cause as Error).message})}finally{setBusy(false)}}
 async function previewClosing(){setBusy(true);try{const body={version:cycleDialog.cycle.version,closing_date:cycleDialog.value};const result=await api(`/cycles/${cycleDialog.cycle.id}/preview-close`,{method:'POST',body:JSON.stringify(body)});setCycleDialog({...cycleDialog,body,result,error:''})}catch(cause){setCycleDialog({...cycleDialog,error:(cause as Error).message})}finally{setBusy(false)}}
 async function applyClosing(){setBusy(true);try{await createOperation(`/cycles/${cycleDialog.cycle.id}/close`,'PATCH',cycleDialog.body)();setCycleDialog(null);await select(selected)}catch(cause){setCycleDialog({...cycleDialog,error:(cause as Error).message})}finally{setBusy(false)}}
 return <>{error&&<div className="error" role="alert">{error}</div>}<div className="row spread section-title"><p>O cartão pode ser de um. A compra fica com quem é responsável.</p><button onClick={()=>{setError('');setForm({name:'',institution:'',holder_id:auth.user.id,closing_day:25,due_day:5})}}><Plus size={17}/>Novo cartão</button></div><div className="grid two">{cards.map((card,index)=><article className="panel payment-card" key={card.id} style={{background:index%2?'#e9eee0':'#244e41',color:index%2?'#35513c':'white'}}><div className="row spread"><CreditCard/><span style={{fontSize:11}}>{card.institution}</span><button aria-label={`Editar ${card.name}`} onClick={()=>setForm(card)}><Pencil size={14}/></button></div><h2 style={{margin:'28px 0 6px'}}>{card.name}</h2><small style={{color:'inherit',opacity:.7}}>{auth.members.find(person=>person.id===card.holder_id)?.name}</small><div className="row spread" style={{marginTop:25,fontSize:12}}><span>Fecha dia <strong>{card.closing_day}</strong></span><span>Vence dia <strong>{card.due_day}</strong></span><button onClick={()=>select(card)}>Ver faturas</button></div></article>)}</div>{!cards.length&&<div className="panel empty">Cadastre seu primeiro cartão para calcular as faturas automaticamente.</div>}
  {selected&&<section className="panel" style={{marginTop:24}}><h3>Faturas · {selected.name}</h3>{!cycles.length&&<p>As faturas aparecerão quando você registrar uma compra neste cartão.</p>}{cycles.map(cycle=><div className="row spread" key={cycle.id} style={{padding:'18px 0',borderBottom:'1px solid var(--line)'}}><div><strong>{monthLabel(cycle.month.slice(0,7))}</strong><span className="subtext">Fechamento {cycle.closing_date} · Vencimento {cycle.due_date}</span><span className={'badge '+(cycle.paid_at?'':'amber')}>{cycle.paid_at?'Paga':cycle.confirmed?'Conferida':'A conferir'}</span></div><div className="actions"><button onClick={()=>setCycleDialog({kind:'closing',cycle,value:cycle.closing_date,error:''})}>Ajustar fechamento</button><button disabled={busy} onClick={()=>cycleAction(cycle,'confirm')}>Conferir</button><button disabled={busy} onClick={()=>cycleAction(cycle,cycle.paid_at?'reopen':'pay')}>{cycle.paid_at?'Reabrir':'Pagar fatura'}</button></div></div>)}</section>}
  {form&&<Modal open onClose={()=>setForm(null)} busy={busy}><ModalHeader>{form.id?'Editar cartão':'Novo cartão'}</ModalHeader><ModalBody><form id="card-form" onSubmit={save}><label>Nome do cartão<input required maxLength={200} value={form.name} onChange={event=>setForm({...form,name:event.target.value})}/></label><label>Instituição<input required maxLength={200} value={form.institution} onChange={event=>setForm({...form,institution:event.target.value})}/></label><label>Titular<select value={form.holder_id} onChange={event=>setForm({...form,holder_id:event.target.value})}>{auth.members.map(person=><option key={person.id} value={person.id}>{person.name}</option>)}</select></label><div className="grid two"><label>Dia do fechamento<input required type="number" min="1" max="31" value={form.closing_day} onChange={event=>setForm({...form,closing_day:Number(event.target.value)})}/></label><label>Dia do vencimento<input required type="number" min="1" max="31" value={form.due_day} onChange={event=>setForm({...form,due_day:Number(event.target.value)})}/></label></div><ModalFormError message={error}/></form></ModalBody><ModalFooter><button onClick={()=>setForm(null)}>Cancelar</button><button className="primary" form="card-form">{busy?'Salvando…':'Salvar cartão'}</button></ModalFooter></Modal>}
  {cycleDialog?.kind==='pay'&&<Modal open onClose={()=>setCycleDialog(null)} busy={busy}><ModalHeader>Pagar fatura</ModalHeader><ModalBody><p>Esta ação abrange a fatura inteira.</p><label>Data do pagamento<input type="date" value={cycleDialog.value} onChange={event=>setCycleDialog({...cycleDialog,value:event.target.value})}/></label><ModalFormError message={cycleDialog.error}/></ModalBody><ModalFooter><button onClick={()=>setCycleDialog(null)}>Cancelar</button><button className="primary" onClick={payInvoice}>{busy?'Salvando…':'Confirmar pagamento'}</button></ModalFooter></Modal>}
  {cycleDialog?.kind==='closing'&&<Modal open onClose={()=>setCycleDialog(null)} busy={busy}><ModalHeader>Conferir mudança de fechamento</ModalHeader><ModalBody>{!cycleDialog.result?<label>Fechamento efetivo<input type="date" value={cycleDialog.value} onChange={event=>setCycleDialog({...cycleDialog,value:event.target.value,result:null})}/></label>:<><p>{cycleDialog.result.changes.length} compras terão a primeira competência alterada.</p><div className="preview-list">{cycleDialog.result.changes.map((change:any)=><div key={change.commitment_id}><span>Compra vinculada</span><strong>{monthLabel(change.first_month.slice(0,7))}</strong></div>)}</div></>}<ModalFormError message={cycleDialog.error}/></ModalBody><ModalFooter><button onClick={()=>setCycleDialog(null)}>Cancelar</button><button className="primary" onClick={cycleDialog.result?applyClosing:previewClosing}>{busy?'Calculando…':cycleDialog.result?'Aplicar alteração':'Conferir fechamento'}</button></ModalFooter></Modal>}
 </>
}
