import {useEffect,useState} from 'react'
import {ArrowUpRight} from 'lucide-react'
import {api,createOperation,money,monthLabel,today} from '../api/client'
import {cents} from '../components/CommitmentForm'
import {ConfirmStep,Modal,ModalBody,ModalClose,ModalFooter,ModalFormError,ModalHeader} from '../components/modal'
import {EditCommitmentModal} from '../components/commitments/EditCommitmentModal'
import {TransferResponsibilityModal} from '../components/commitments/TransferResponsibilityModal'

type Member={id:string;name:string}
type Action={kind:'edit'|'transfer'|'shift'|'delete'}|{kind:'pay'|'cancel'|'reopen';plan:any}

export function Commitment({id,members=[],onClose,onChanged}:{id:string;members?:Member[];onClose:()=>void;onChanged:()=>void}){
 const [availableMembers,setAvailableMembers]=useState(members),[data,setData]=useState<any>(null),[cards,setCards]=useState<any[]>([]),[plans,setPlans]=useState<any[]>([]),[selected,setSelected]=useState<string[]>([]),[plannedDate,setDate]=useState(today()),[amount,setAmount]=useState(''),[preview,setPreview]=useState<any>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[action,setAction]=useState<Action|null>(null)
 async function load(){const [detail,advances,availableCards]=await Promise.all([api(`/commitments/${id}`),api('/advances'),api('/cards')]);setData(detail);setCards(availableCards);setPlans(advances.filter((item:any)=>item.commitment_id===id))}
 useEffect(()=>{load().catch(cause=>setError((cause as Error).message));if(!members.length)api<{members:Member[]}>('/auth/me').then(auth=>setAvailableMembers(auth.members)).catch(cause=>setError((cause as Error).message))},[id])
 async function run(operation:()=>Promise<any>,after?:()=>void){setBusy(true);setError('');try{await operation();await load();onChanged();setAction(null);after?.()}catch(cause){setError((cause as Error).message)}finally{setBusy(false)}}
 const payload=()=>({commitment_id:id,version:data.version,installment_ids:selected,planned_date:plannedDate,amount_cents:cents(amount)})
 async function inspectAdvance(){try{setPreview(await api('/advances/preview',{method:'POST',body:JSON.stringify(payload())}));setError('')}catch(cause){setError((cause as Error).message)}}
 const actionSaved=async()=>{setAction(null);await load();onChanged()}
 if(data&&action?.kind==='edit')return <EditCommitmentModal open commitment={data} members={availableMembers} cards={cards} onClose={()=>setAction(null)} onSaved={actionSaved}/>
 if(data&&action?.kind==='transfer')return <TransferResponsibilityModal open commitmentId={id} version={data.version} openTotalCents={data.installments.filter((part:any)=>!part.paid_at).reduce((sum:number,part:any)=>sum+part.amount_cents,0)} currentShares={aggregateOpenShares(data.installments)} members={availableMembers} onClose={()=>setAction(null)} onSaved={actionSaved}/>
 if(data&&action?.kind==='shift')return <ShiftModal commitment={data} busy={busy} error={error} onClose={()=>setAction(null)} onConfirm={body=>run(()=>createOperation(`/commitments/${id}/shift`,'POST',body)())}/>
 if(data&&action?.kind==='pay')return <PaymentModal title="Registrar pagamento" busy={busy} error={error} onClose={()=>setAction(null)} onConfirm={paidAt=>run(()=>createOperation(`/advances/${action.plan.id}/pay`,'POST',{version:action.plan.version,paid_at:paidAt})())}/>
 if(data&&action?.kind==='cancel')return <ConfirmAction title="Cancelar antecipação?" description="As parcelas voltarão ao cronograma normal e o planejamento será removido." label="Confirmar cancelamento" busy={busy} error={error} onClose={()=>setAction(null)} onConfirm={()=>run(()=>createOperation(`/advances/${action.plan.id}/cancel`,'POST',{version:action.plan.version})())}/>
 if(data&&action?.kind==='reopen')return <ConfirmAction title="Reabrir antecipação?" description="O pagamento será desfeito e as parcelas voltarão a ficar abertas." label="Confirmar reabertura" busy={busy} error={error} onClose={()=>setAction(null)} onConfirm={()=>run(()=>createOperation(`/advances/${action.plan.id}/reopen`,'POST',{version:action.plan.version})())}/>
 if(data&&action?.kind==='delete')return <ConfirmAction title="Excluir compromisso?" description="Todas as parcelas e o histórico desse compromisso serão removidos." label="Excluir compromisso" busy={busy} error={error} onClose={()=>setAction(null)} onConfirm={()=>run(()=>createOperation(`/commitments/${id}?version=${data.version}&confirm=true`,'DELETE')(),onClose)}/>
 return <Modal open onClose={onClose} busy={busy}>
  <ModalHeader description="Cada parcela mantém seu próprio histórico.">{data?.description??'Carregando…'}</ModalHeader>
  <ModalBody><ModalFormError message={error}/>{data&&<>
   <div className="grid two" style={{margin:'20px 0'}}><div className="panel"><small>Contrato original</small><h2>{data.original_count} parcelas</h2></div><div className="panel"><small>Obrigações pendentes</small><h2 data-testid="pending-count">{data.pending_count}</h2><small>Última parcela em aberto: {data.last_open_number??'Nenhuma'}</small></div></div>
   {data.imported&&<p className="form-help">Compromisso importado. O histórico anterior não foi reconstruído.</p>}
   <div className="actions" style={{margin:'15px 0'}}><button onClick={()=>setAction({kind:'shift'})}>Ajustar competência</button><button onClick={()=>setAction({kind:'edit'})}>Editar lançamento</button><button onClick={()=>setAction({kind:'transfer'})}>Transferir responsabilidade</button><button onClick={()=>setAction({kind:'delete'})}>Excluir compromisso</button></div>
   <h3 style={{margin:'22px 0 10px'}}>Selecione as parcelas para antecipar</h3><div className="preview-list">{data.installments.map((part:any)=>{const active=plans.some(plan=>plan.state!=='cancelled'&&plan.items.some((item:any)=>item.installment_id===part.id));return <div key={part.id}><label className="checkbox-row"><input type="checkbox" aria-label={`Selecionar parcela ${part.number}`} disabled={Boolean(part.paid_at)||active} checked={selected.includes(part.id)} onChange={event=>{setSelected(current=>event.target.checked?[...current,part.id]:current.filter(item=>item!==part.id));setPreview(null)}}/><span>Parcela {part.number}/{data.original_count}<small className="subtext">{monthLabel(part.month.slice(0,7))}{part.month!==part.original_month?` · Original: ${monthLabel(part.original_month.slice(0,7))}`:''}</small></span></label><div className="text-right"><strong>{money(part.amount_cents)}</strong><span className="subtext">{part.paid_at?'Paga':active?'Antecipação planejada':'Em aberto'}</span></div></div>})}</div>
   {selected.length>0&&<section style={{marginTop:20}}><div className="grid two"><label>Data prevista para antecipar<input type="date" value={plannedDate} onChange={event=>{setDate(event.target.value);setPreview(null)}}/></label><label>Valor final com desconto (R$)<input type="number" min="0.01" step="0.01" value={amount} onChange={event=>{setAmount(event.target.value);setPreview(null)}}/></label></div><p className="form-help" style={{margin:'12px 0'}}>Informe o valor oferecido pelo banco. Desconto zero também é aceito.</p>{preview?<div className="panel"><p>Original: {money(preview.original_cents)} · Desconto: {money(preview.discount_cents)}</p><strong>{money(preview.amount_cents)} em {monthLabel(preview.month.slice(0,7))}</strong><button className="primary" disabled={busy} onClick={()=>run(async()=>{await createOperation('/advances','POST',payload())();setPreview(null);setSelected([])})} style={{marginTop:15}}>Planejar antecipação</button></div>:<button onClick={inspectAdvance}>Conferir antecipação<ArrowUpRight size={16}/></button>}</section>}
   {plans.length>0&&<section style={{marginTop:24}}><h3>Histórico de antecipações</h3>{plans.map(plan=><div className="panel" key={plan.id} style={{marginTop:12}}><div className="row spread"><strong>{money(plan.amount_cents)} · {monthLabel(plan.month.slice(0,7))}</strong><span className="badge">{({planned:'Planejada',paid:'Paga',cancelled:'Cancelada'} as any)[plan.state]}</span></div><div>{plan.items.map((item:any)=>{const part=data.installments.find((candidate:any)=>candidate.id===item.installment_id);return part&&<small className="subtext" key={item.id}>Parcela {part.number}/{data.original_count} · Competência original: {monthLabel(part.original_month.slice(0,7))}</small>})}</div><p>Original: {money(plan.items.reduce((sum:number,item:any)=>sum+item.snapshot.amount_cents,0))} · Desconto: {money(plan.items.reduce((sum:number,item:any)=>sum+item.snapshot.amount_cents,0)-plan.amount_cents)}</p><div className="actions" style={{marginTop:12}}>{plan.state==='planned'&&<><button disabled={busy} onClick={()=>setAction({kind:'pay',plan})}>{data.card_id?'Pagamento pela fatura':'Registrar pagamento'}</button><button disabled={busy} onClick={()=>setAction({kind:'cancel',plan})}>Cancelar antecipação</button></>}{plan.state==='paid'&&<button disabled={busy} onClick={()=>setAction({kind:'reopen',plan})}>Reabrir antecipação</button>}</div></div>)}</section>}
  </>}</ModalBody><ModalFooter><ModalClose>Fechar detalhes</ModalClose></ModalFooter>
 </Modal>
}

function aggregateOpenShares(parts:any[]){const totals=new Map<string,number>();for(const part of parts.filter(item=>!item.paid_at))for(const share of part.shares??[])totals.set(share.user_id,(totals.get(share.user_id)??0)+share.weight);return [...totals].map(([user_id,weight])=>({user_id,weight}))}
function ConfirmAction({title,description,label,busy,error,onClose,onConfirm}:{title:string;description:string;label:string;busy:boolean;error:string;onClose:()=>void;onConfirm:()=>void}){return <Modal open onClose={onClose} busy={busy}><ConfirmStep title={title} description={description} confirmLabel={label} onCancel={onClose} onConfirm={onConfirm}/><ModalFormError message={error}/></Modal>}
function ShiftModal({commitment,busy,error,onClose,onConfirm}:{commitment:any;busy:boolean;error:string;onClose:()=>void;onConfirm:(body:any)=>void}){const [month,setMonth]=useState(commitment.installments[0]?.month.slice(0,7)??''),[preview,setPreview]=useState<any>(null),[localError,setLocalError]=useState('');async function inspect(){try{setPreview(await api(`/commitments/${commitment.id}/preview-shift`,{method:'POST',body:JSON.stringify({version:commitment.version,first_month:month+'-01'})}));setLocalError('')}catch(cause){setLocalError((cause as Error).message)}}return <Modal open onClose={onClose} busy={busy}><ModalHeader>Ajustar competência</ModalHeader><ModalBody><label>Primeira competência<input type="month" value={month} onChange={event=>{setMonth(event.target.value);setPreview(null)}}/></label><ModalFormError message={localError||error}/>{preview&&<div className="panel">Parcelas serão reorganizadas para: {preview.installments.map((part:any)=>monthLabel(part.month.slice(0,7))).join(', ')}</div>}</ModalBody><ModalFooter><button onClick={onClose}>Cancelar</button>{preview?<button className="primary" onClick={()=>onConfirm({version:commitment.version,first_month:month+'-01'})}>Confirmar ajuste</button>:<button className="primary" onClick={inspect}>Conferir competências</button>}</ModalFooter></Modal>}
function PaymentModal({title,busy,error,onClose,onConfirm}:{title:string;busy:boolean;error:string;onClose:()=>void;onConfirm:(date:string)=>void}){const [paidAt,setPaidAt]=useState(today());return <Modal open onClose={onClose} busy={busy}><ModalHeader>{title}</ModalHeader><ModalBody><label>Data do pagamento<input type="date" value={paidAt} onChange={event=>setPaidAt(event.target.value)}/></label><ModalFormError message={error}/></ModalBody><ModalFooter><button onClick={onClose}>Cancelar</button><button className="primary" onClick={()=>onConfirm(paidAt)}>Confirmar pagamento</button></ModalFooter></Modal>}
