import {useEffect,useRef,useState} from 'react'
import {ArrowDownLeft,ArrowUpRight,Wallet,ChevronLeft,ChevronRight,Check,CalendarDays} from 'lucide-react'
import {api,createOperation,money,monthLabel,today} from '../api/client'
import type {Auth} from '../App'
import {ConfirmStep,Modal,ModalBody,ModalFooter,ModalFormError,ModalHeader} from '../components/modal'
export function Overview({auth,onOpen,refresh,selectedMonth,onMonthChange,view='summary',onShowEntries}:{auth:Auth,onOpen:(id:string)=>void,refresh:number,selectedMonth?:string,onMonthChange?:(month:string)=>void,view?:'summary'|'entries',onShowEntries?:()=>void}){
 const [search,setSearch]=useState('')
 const [localMonth,setLocalMonth]=useState('default')
 const month=selectedMonth??localMonth,setMonth=onMonthChange??setLocalMonth
 const [data,setData]=useState<any>(null),[person,setPerson]=useState(''),[filter,setFilter]=useState('all'),[error,setError]=useState(''),[revision,setRevision]=useState(0),[action,setAction]=useState<any>(null),[busy,setBusy]=useState(false)
 const sequence=useRef(0)
 useEffect(()=>{const current=++sequence.current;api(`/months/${month}${person?'?person_id='+person:''}`).then(d=>{if(current===sequence.current){setData(d);if(month==='default')setMonth(d.month);setError('')}}).catch(e=>setError(e.message))},[month,person,refresh,revision])
 function shift(offset:number){if(!data)return;const d=new Date(data.month+'-01T12:00:00Z');d.setUTCMonth(d.getUTCMonth()+offset);setMonth(d.toISOString().slice(0,7))}
 async function beginPay(item:any){try{let path,version=item.version,scope=`Somente “${item.description}” será marcado como pago.`
  if(item.cycle_id){const cycles=await api(`/cards/${item.card_id}/cycles`);version=cycles.find((cycle:any)=>cycle.id===item.cycle_id).version;path=`/invoices/${item.cycle_id}`;scope='A fatura inteira será marcada como paga.'}
  else path=`/${item.kind==='occurrence'?'occurrences':'installments'}/${item.id}`
  setAction({kind:item.paid_at?'reopen':'pay',item,path,version,scope,paidAt:today(),error:''})
 }catch(cause){setError((cause as Error).message)}}
 async function performAction(){setBusy(true);setAction((current:any)=>({...current,error:''}));try{await createOperation(action.path+(action.kind==='reopen'?'/reopen':'/pay'),'POST',{version:action.version,...(action.kind==='pay'?{paid_at:action.paidAt}:{})})();setAction(null);setRevision(value=>value+1)}catch(cause){setAction((current:any)=>({...current,error:(cause as Error).message}))}finally{setBusy(false)}}
 async function closeMonth(){setBusy(true);try{await createOperation(`/months/${data.month}/close`,'POST',{})();setRevision(value=>value+1);setAction({kind:'monthDone'})}catch(cause){setAction((current:any)=>({...current,error:(cause as Error).message}))}finally{setBusy(false)}}
 if(!data)return <div className="panel">{error?<div role="alert" className="error">{error}</div>:'Carregando seu mês…'}</div>
 const filtered=data.items.filter((i:any)=>i.description.toLocaleLowerCase('pt-BR').includes(search.toLocaleLowerCase('pt-BR'))&&(filter==='all'||(filter==='paid'?i.paid_at:!i.paid_at)))
 const items=view==='summary'?data.items.filter((i:any)=>!i.paid_at).slice(0,5):filtered
 const nextMonth=new Date(data.current_month+'-01T12:00:00Z');nextMonth.setUTCMonth(nextMonth.getUTCMonth()+1)
 const label=data.month===data.current_month?'Mês atual':data.month===nextMonth.toISOString().slice(0,7)?'Próximo mês':data.month>data.current_month?'Planejamento':'Histórico'
 function title(item:any){return <><strong>{item.description}</strong><span className="subtext">{item.advance_id?`Antecipação · parcela ${item.number}/${item.original_count}`:item.number?`Parcela ${item.number}/${item.original_count}${item.number===item.original_count?' · Última parcela':''}`:'Conta da casa'}{item.needs_review?' · Conferir fatura':''}</span></>}
 function state(item:any){return <span className={'badge '+(item.paid_at?'':item.estimated?'blue':'amber')}>{item.paid_at?'Pago':item.advance_id?'Antecipação planejada':item.estimated?'Estimado':'Previsto'}</span>}
 return <><div className="row spread"><div className="month-control"><button aria-label="Mês anterior" onClick={()=>shift(-1)}><ChevronLeft size={18}/></button><CalendarDays size={17}/><input aria-label="Competência" type="month" value={data.month} onChange={e=>e.target.value&&setMonth(e.target.value)}/><button aria-label="Próximo mês" onClick={()=>shift(1)}><ChevronRight size={18}/></button><span className="badge">{label}</span></div><span className="muted" style={{fontSize:11}}>Um olhar para o que já está comprometido</span></div>
 {error&&<div role="alert" className="error" style={{marginTop:15}}>{error}</div>}
 {data.month!==data.current_month&&data.current_remaining>0&&<div className="notice" style={{marginTop:18}}>Ainda há <strong>{money(data.current_remaining)}</strong> pendentes em {monthLabel(data.current_month)}. <button className="link-button" onClick={()=>setMonth(data.current_month)}>Ver mês atual <ArrowUpRight size={14}/></button></div>}
 {view==='summary'&&<><div className="stat-grid"><div className="stat featured"><Wallet size={20} className="stat-icon"/><span>Total previsto {person?'da pessoa':'da família'}</span><strong data-testid="expected">{money(data.totals.expected)}</strong><small>{monthLabel(data.month)} · compromissos conhecidos</small></div><div className="stat"><ArrowDownLeft size={20} className="stat-icon"/><span>Já foi pago</span><strong data-testid="paid">{money(data.totals.paid)}</strong><small>Um passo a menos para este mês</small></div><div className="stat"><ArrowUpRight size={20} className="stat-icon"/><span>Ainda falta pagar</span><strong data-testid="remaining">{money(data.totals.remaining)}</strong><small>Inclui despesas estimadas</small></div></div>
 <div className="person-strip">{auth.members.map((p,index)=>{const amount=data.people.find((x:any)=>x.id===p.id)?.amount_cents??0;return <div className="person-card" key={p.id}><div className="avatar" style={index?{background:'#f0e9df',color:'#a58963'}:{}}>{p.name[0]}</div><div><span className="person-name">Responsabilidade de</span><strong>{p.name}</strong></div><div className="person-amount"><strong>{money(amount)}</strong><div className="progress"><span style={{width:`${data.family_total?amount/data.family_total*100:0}%`}}/></div></div></div>})}</div></>}
 <section className="panel"><div className="toolbar"><div><h3>{view==='summary'?'Pendências do mês':'Lançamentos do mês'}</h3><p style={{fontSize:11,margin:'5px 0'}}>{view==='summary'?`${items.length} pendências em destaque`:`${items.length} lançamentos encontrados · ${money(filtered.reduce((total:number,i:any)=>total+i.display_cents,0))}`}</p></div>{view==='entries'&&<select aria-label="Filtrar pessoa" value={person} onChange={e=>setPerson(e.target.value)}><option value="">Toda a família</option>{auth.members.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select>}</div>{view==='entries'&&<label className="entry-search">Pesquisar lançamentos<input type="search" placeholder="Buscar pela descrição" value={search} onChange={e=>setSearch(e.target.value)}/></label>}<div className="row spread" style={{margin:'20px 0 4px'}}>{view==='entries'&&<div className="filters">{[['all','Todos'],['open','A pagar'],['paid','Pagos']].map(([value,label])=><button key={value} className={filter===value?'selected':''} onClick={()=>setFilter(value)}>{label}</button>)}</div>}<button className="link-button" style={{fontSize:11}} onClick={()=>setAction({kind:'month',error:''})}><Check size={15}/>Tudo deste mês foi pago</button></div>
 {!items.length?<div className="empty">{view==='summary'?'Nenhuma pendência neste mês.':'Nenhum lançamento encontrado.'}<br/><small>Use “Adicionar despesa” para registrar seus gastos.</small></div>:<><div className="desktop-only table-wrap"><table><thead><tr><th>Descrição</th><th>Responsável</th><th>Situação</th><th className="text-right">Valor</th><th/></tr></thead><tbody>{items.map((item:any)=><tr key={item.id}><td><button className="link-button" onClick={()=>item.commitment_id&&onOpen(item.commitment_id)}><div>{title(item)}</div></button></td><td>{item.shares.filter((s:any)=>s.amount_cents).map((s:any)=>s.name).join(' / ')}</td><td>{state(item)}</td><td className="text-right"><strong>{money(item.display_cents)}</strong></td><td><button aria-label={`${item.paid_at?'Reabrir':'Pagar'} ${item.description}`} onClick={()=>beginPay(item)}>{item.paid_at?'Reabrir':'Pagar'}</button></td></tr>)}</tbody></table></div><div className="mobile-only">{items.map((item:any)=><article className="expense-mobile" key={item.id}><div className="row"><button className="link-button" onClick={()=>item.commitment_id&&onOpen(item.commitment_id)}><div>{title(item)}</div></button><strong className="amount">{money(item.display_cents)}</strong></div><div className="row spread"><small>{item.shares.filter((s:any)=>s.amount_cents).map((s:any)=>s.name).join(' / ')}</small>{state(item)}</div><div className="actions"><button aria-label={`${item.paid_at?'Reabrir':'Pagar'} ${item.description}`} onClick={()=>beginPay(item)}>{item.paid_at?'Reabrir':'Pagar'}</button></div></article>)}</div></>}
 {view==='summary'&&onShowEntries&&<button style={{marginTop:16}} onClick={onShowEntries}>Ver todos os lançamentos</button>}</section><p style={{fontSize:10,textAlign:'center',marginTop:22}}>Mais clareza para decidir. Mais espaço para os planos de vocês.</p>{action&&<OverviewActionModal action={action} month={data.month} busy={busy} setAction={setAction} onConfirm={action.kind==='month'?closeMonth:performAction} onNext={()=>{setAction(null);shift(1)}}/>}</>
}

function OverviewActionModal({action,month,busy,setAction,onConfirm,onNext}:{action:any;month:string;busy:boolean;setAction:(value:any)=>void;onConfirm:()=>void;onNext:()=>void}){
 if(action.kind==='monthDone')return <Modal open onClose={()=>setAction(null)}><ModalHeader>Mês sinalizado como quitado.</ModalHeader><ModalBody><p>Os lançamentos de {monthLabel(month)} foram conferidos.</p></ModalBody><ModalFooter><button onClick={()=>setAction(null)}>Ficar neste mês</button><button className="primary" onClick={onNext}>Abrir próximo mês</button></ModalFooter></Modal>
 if(action.kind==='month')return <Modal open onClose={()=>setAction(null)} busy={busy}><ConfirmStep title="Fechar mês?" description={`Esta ação vai sinalizar ${monthLabel(month)} como quitado.`} confirmLabel={busy?'Fechando…':'Confirmar fechamento'} onCancel={()=>setAction(null)} onConfirm={onConfirm}/><ModalFormError message={action.error}/></Modal>
 const reopening=action.kind==='reopen'
 return <Modal open onClose={()=>setAction(null)} busy={busy}><ModalHeader>{reopening?'Reabrir pagamento':'Registrar pagamento'}</ModalHeader><ModalBody><p>{reopening?`O pagamento de “${action.item.description}” será desfeito.`:action.scope}</p>{!reopening&&<label>Data do pagamento<input type="date" value={action.paidAt} onChange={event=>setAction({...action,paidAt:event.target.value})}/></label>}<ModalFormError message={action.error}/></ModalBody><ModalFooter><button onClick={()=>setAction(null)}>Cancelar</button><button className="primary" onClick={onConfirm}>{busy?'Salvando…':reopening?'Confirmar reabertura':'Confirmar pagamento'}</button></ModalFooter></Modal>
}
