import {useEffect,useRef,useState} from 'react'
import {ArrowDownLeft,ArrowUpRight,Wallet,ChevronLeft,ChevronRight,Check,CalendarDays} from 'lucide-react'
import {api,createOperation,money,monthLabel,today} from '../api/client'
import type {Auth} from '../App'
export function Overview({auth,onOpen,refresh,selectedMonth,onMonthChange}:{auth:Auth,onOpen:(id:string)=>void,refresh:number,selectedMonth?:string,onMonthChange?:(month:string)=>void}){
 const [localMonth,setLocalMonth]=useState('default')
 const month=selectedMonth??localMonth,setMonth=onMonthChange??setLocalMonth
 const [data,setData]=useState<any>(null),[person,setPerson]=useState(''),[filter,setFilter]=useState('all'),[error,setError]=useState(''),[revision,setRevision]=useState(0)
 const sequence=useRef(0)
 useEffect(()=>{const current=++sequence.current;api(`/months/${month}${person?'?person_id='+person:''}`).then(d=>{if(current===sequence.current){setData(d);if(month==='default')setMonth(d.month);setError('')}}).catch(e=>setError(e.message))},[month,person,refresh,revision])
 function shift(offset:number){if(!data)return;const d=new Date(data.month+'-01T12:00:00Z');d.setUTCMonth(d.getUTCMonth()+offset);setMonth(d.toISOString().slice(0,7))}
 async function pay(item:any){try{let path,version=item.version
  if(item.cycle_id){const cycles=await api(`/cards/${item.card_id}/cycles`);version=cycles.find((c:any)=>c.id===item.cycle_id).version;path=`/invoices/${item.cycle_id}`;if(!window.confirm('Esta ação abrange a fatura inteira. Continuar?'))return}
  else path=`/${item.kind==='occurrence'?'occurrences':'installments'}/${item.id}`
  const paid_at=item.paid_at?undefined:window.prompt('Data do pagamento (AAAA-MM-DD)',today());if(!item.paid_at&&!paid_at)return
  await createOperation(path+(item.paid_at?'/reopen':'/pay'),'POST',{version,paid_at})();setRevision(x=>x+1)
 }catch(e){setError((e as Error).message)}}
 async function close(){try{await createOperation(`/months/${data.month}/close`,'POST',{})();setRevision(x=>x+1);if(window.confirm('Mês sinalizado como quitado. Abrir o próximo mês?'))shift(1)}catch(e){setError((e as Error).message)}}
 if(!data)return <div className="panel">{error?<div role="alert" className="error">{error}</div>:'Carregando seu mês…'}</div>
 const items=data.items.filter((i:any)=>filter==='all'||(filter==='paid'?i.paid_at:!i.paid_at))
 const nextMonth=new Date(data.current_month+'-01T12:00:00Z');nextMonth.setUTCMonth(nextMonth.getUTCMonth()+1)
 const label=data.month===data.current_month?'Mês atual':data.month===nextMonth.toISOString().slice(0,7)?'Próximo mês':data.month>data.current_month?'Planejamento':'Histórico'
 function title(item:any){return <><strong>{item.description}</strong><span className="subtext">{item.advance_id?`Antecipação · parcela ${item.number}/${item.original_count}`:item.number?`Parcela ${item.number}/${item.original_count}${item.number===item.original_count?' · Última parcela':''}`:'Conta da casa'}{item.needs_review?' · Conferir fatura':''}</span></>}
 function state(item:any){return <span className={'badge '+(item.paid_at?'':item.estimated?'blue':'amber')}>{item.paid_at?'Pago':item.advance_id?'Antecipação planejada':item.estimated?'Estimado':'Previsto'}</span>}
 return <><div className="row spread"><div className="month-control"><button aria-label="Mês anterior" onClick={()=>shift(-1)}><ChevronLeft size={18}/></button><CalendarDays size={17}/><input aria-label="Competência" type="month" value={data.month} onChange={e=>e.target.value&&setMonth(e.target.value)}/><button aria-label="Próximo mês" onClick={()=>shift(1)}><ChevronRight size={18}/></button><span className="badge">{label}</span></div><span className="muted" style={{fontSize:11}}>Um olhar para o que já está comprometido</span></div>
 {error&&<div role="alert" className="error" style={{marginTop:15}}>{error}</div>}
 {data.month!==data.current_month&&data.current_remaining>0&&<div className="notice" style={{marginTop:18}}>Ainda há <strong>{money(data.current_remaining)}</strong> pendentes em {monthLabel(data.current_month)}. <button className="link-button" onClick={()=>setMonth(data.current_month)}>Ver mês atual <ArrowUpRight size={14}/></button></div>}
 <div className="stat-grid"><div className="stat featured"><Wallet size={20} className="stat-icon"/><span>Total previsto {person?'da pessoa':'da família'}</span><strong data-testid="expected">{money(data.totals.expected)}</strong><small>{monthLabel(data.month)} · compromissos conhecidos</small></div><div className="stat"><ArrowDownLeft size={20} className="stat-icon"/><span>Já foi pago</span><strong data-testid="paid">{money(data.totals.paid)}</strong><small>Um passo a menos para este mês</small></div><div className="stat"><ArrowUpRight size={20} className="stat-icon"/><span>Ainda falta pagar</span><strong data-testid="remaining">{money(data.totals.remaining)}</strong><small>Inclui despesas estimadas</small></div></div>
 <div className="person-strip">{auth.members.map((p,index)=>{const amount=data.people.find((x:any)=>x.id===p.id)?.amount_cents??0;return <div className="person-card" key={p.id}><div className="avatar" style={index?{background:'#f0e9df',color:'#a58963'}:{}}>{p.name[0]}</div><div><span className="person-name">Responsabilidade de</span><strong>{p.name}</strong></div><div className="person-amount"><strong>{money(amount)}</strong><div className="progress"><span style={{width:`${data.family_total?amount/data.family_total*100:0}%`}}/></div></div></div>})}</div>
 <section className="panel"><div className="toolbar"><div><h3>Despesas do mês</h3><p style={{fontSize:11,margin:'5px 0'}}>{items.length} lançamentos · cada compromisso no seu lugar</p></div><select aria-label="Filtrar pessoa" value={person} onChange={e=>setPerson(e.target.value)}><option value="">Toda a família</option>{auth.members.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></div><div className="row spread" style={{margin:'20px 0 4px'}}><div className="filters">{[['all','Todos'],['open','A pagar'],['paid','Pagos']].map(([value,label])=><button key={value} className={filter===value?'selected':''} onClick={()=>setFilter(value)}>{label}</button>)}</div><button className="link-button" style={{fontSize:11}} onClick={close}><Check size={15}/>Tudo deste mês foi pago</button></div>
 {!items.length?<div className="empty">Nenhuma despesa por aqui.<br/><small>Use “Adicionar gasto” para começar seu planejamento.</small></div>:<><div className="desktop-only table-wrap"><table><thead><tr><th>Descrição</th><th>Responsável</th><th>Situação</th><th className="text-right">Valor</th><th/></tr></thead><tbody>{items.map((item:any)=><tr key={item.id}><td><button className="link-button" onClick={()=>item.commitment_id&&onOpen(item.commitment_id)}><div>{title(item)}</div></button></td><td>{item.shares.filter((s:any)=>s.amount_cents).map((s:any)=>s.name).join(' / ')}</td><td>{state(item)}</td><td className="text-right"><strong>{money(item.display_cents)}</strong></td><td><button aria-label={`${item.paid_at?'Reabrir':'Pagar'} ${item.description}`} onClick={()=>pay(item)}>{item.paid_at?'Reabrir':'Pagar'}</button></td></tr>)}</tbody></table></div><div className="mobile-only">{items.map((item:any)=><article className="expense-mobile" key={item.id}><div className="row"><button className="link-button" onClick={()=>item.commitment_id&&onOpen(item.commitment_id)}><div>{title(item)}</div></button><strong className="amount">{money(item.display_cents)}</strong></div><div className="row spread"><small>{item.shares.filter((s:any)=>s.amount_cents).map((s:any)=>s.name).join(' / ')}</small>{state(item)}</div><div className="actions"><button aria-label={`${item.paid_at?'Reabrir':'Pagar'} ${item.description}`} onClick={()=>pay(item)}>{item.paid_at?'Reabrir':'Pagar'}</button></div></article>)}</div></>}
 </section><p style={{fontSize:10,textAlign:'center',marginTop:22}}>Mais clareza para decidir. Mais espaço para os planos de vocês.</p></>
}
