import {useEffect,useState} from 'react'
import type {Auth} from '../App'
import {api,money,monthLabel,today} from '../api/client'
export function Planning({refresh=0}:{auth:Auth,onChanged:()=>void,refresh?:number}){
 const [from,setFrom]=useState(today().slice(0,7)),[forecast,setForecast]=useState<any[]>([]),[error,setError]=useState('')
 useEffect(()=>{api(`/forecast?from_month=${from}&months=12`).then(setForecast).catch(e=>setError(e.message))},[from,refresh])
 const maximum=Math.max(1,...forecast.map(m=>m.totals.expected))
 return <>{error&&<div role="alert" className="error">{error}</div>}<section className="panel"><div className="toolbar"><div><h3>Os próximos 12 meses</h3><p style={{fontSize:12}}>O que já está comprometido, antes de fazer novos planos.</p></div><label>Começando em<input aria-label="Início da projeção" type="month" value={from} onChange={e=>e.target.value&&setFrom(e.target.value)}/></label></div><div className="forecast-bars">{forecast.map(m=><div className="forecast-column" key={m.month} title={`${monthLabel(m.month)}: ${money(m.totals.expected)}`}><div className="bar" style={{height:Math.max(3,m.totals.expected/maximum*125)}}/><span>{new Date(m.month+'-01T12:00:00Z').toLocaleDateString('pt-BR',{month:'short',timeZone:'UTC'})}</span></div>)}</div><div className="table-wrap"><table><thead><tr><th>Mês</th><th>Previsto</th><th>Estimativas</th><th>Parcelas que terminam</th></tr></thead><tbody>{forecast.map(m=><tr key={m.month}><td>{monthLabel(m.month)}</td><td>{money(m.totals.expected)}</td><td>{m.items.some((i:any)=>i.estimated)?<span className="badge blue">Inclui estimativas</span>:'—'}</td><td>{m.items.filter((i:any)=>i.number&&i.number===i.original_count).map((i:any)=><div key={i.id}>{i.description} · {i.number}/{i.original_count}</div>)}</td></tr>)}</tbody></table></div></section></>
}
