import React from 'react'
import {cleanup,fireEvent,render,screen,waitFor} from '@testing-library/react'
import {afterEach,describe,expect,it,vi} from 'vitest'
import {api,createOperation} from '../api/client'
import {RecurrenceManager} from './RecurrenceManager'
vi.mock('../api/client',async()=>({...await vi.importActual('../api/client'),api:vi.fn(),createOperation:vi.fn()}))
const occurrence={id:'o1',version:2,month:'2026-10-01',amount_cents:12345,estimated:true}
const rule={id:'r1',version:3,description:'Energia',amount_cents:12345,due_day:10,variable:true,end_month:null,occurrences:[occurrence]}
function setup(){vi.mocked(api).mockResolvedValue([rule]);return render(<RecurrenceManager month="2026-10" refresh={0} onChanged={vi.fn()}/>)}
afterEach(()=>{cleanup();vi.clearAllMocks()})
describe('MODAL-01 recurring actions',()=>{
 it('opens a value modal with the current amount preserved',async()=>{setup();fireEvent.click(await screen.findByRole('button',{name:'Ajustar valor'}));expect((screen.getByLabelText('Valor da conta (R$)') as HTMLInputElement).value).toBe('123.45')})
 it('saves the adjusted amount in cents through the existing contract',async()=>{vi.mocked(createOperation).mockReturnValue(vi.fn().mockResolvedValue({}));setup();fireEvent.click(await screen.findByRole('button',{name:'Ajustar valor'}));fireEvent.change(screen.getByLabelText('Valor da conta (R$)'),{target:{value:'150.25'}});fireEvent.click(screen.getByRole('button',{name:'Salvar valor'}));await waitFor(()=>expect(createOperation).toHaveBeenCalledWith('/occurrences/o1','PATCH',{version:2,amount_cents:15025}))})
 it('prefills and confirms the recurrence ending month',async()=>{vi.mocked(createOperation).mockReturnValue(vi.fn().mockResolvedValue({}));setup();fireEvent.click(await screen.findByRole('button',{name:'Encerrar recorrência'}));expect((screen.getByLabelText('Encerrar a partir de') as HTMLInputElement).value).toBe('2026-10');fireEvent.change(screen.getByLabelText('Encerrar a partir de'),{target:{value:'2026-12'}});fireEvent.click(screen.getByRole('button',{name:'Confirmar encerramento'}));await waitFor(()=>expect(createOperation).toHaveBeenCalledWith('/recurrences/r1/end','POST',{version:3,end_month:'2026-12-01'}))})
 it('uses an internal destructive confirmation with the exact impact',async()=>{setup();fireEvent.click(await screen.findByRole('button',{name:'Excluir recorrência'}));expect(screen.getByText('A recorrência “Energia” e suas ocorrências serão excluídas. Pagamentos registrados precisam ser reabertos antes.')).toBeTruthy()})
 it('keeps the typed value visible when the mutation fails',async()=>{vi.mocked(createOperation).mockReturnValue(vi.fn().mockRejectedValue(new Error('Pagamento registrado impede alteração.')));setup();fireEvent.click(await screen.findByRole('button',{name:'Ajustar valor'}));fireEvent.change(screen.getByLabelText('Valor da conta (R$)'),{target:{value:'180'}});fireEvent.click(screen.getByRole('button',{name:'Salvar valor'}));expect((await screen.findByRole('alert')).textContent).toContain('Pagamento registrado');expect((screen.getByLabelText('Valor da conta (R$)') as HTMLInputElement).value).toBe('180')})
 it('disables duplicate mutations while saving and never invokes native dialogs',async()=>{const prompt=vi.spyOn(window,'prompt'),confirm=vi.spyOn(window,'confirm'),alert=vi.spyOn(window,'alert');let finish:(value:unknown)=>void=()=>{};vi.mocked(createOperation).mockReturnValue(vi.fn(()=>new Promise(resolve=>{finish=resolve})));setup();fireEvent.click(await screen.findByRole('button',{name:'Ajustar valor'}));fireEvent.click(screen.getByRole('button',{name:'Salvar valor'}));expect((screen.getByRole('button',{name:'Salvando…'}) as HTMLButtonElement).disabled).toBe(true);expect(prompt).not.toHaveBeenCalled();expect(confirm).not.toHaveBeenCalled();expect(alert).not.toHaveBeenCalled();finish({})})
})
