import {useEffect,useState} from 'react'
import {api,createOperation,money,monthLabel} from '../api/client'
import {cents} from '../components/CommitmentForm'
import {ConfirmStep,Modal,ModalBody,ModalFooter,ModalFormError,ModalHeader} from '../components/modal'

export function RecurrenceManager({month,refresh,onChanged}:{month:string;refresh:number;onChanged:()=>void}){
 const [rules,setRules]=useState<any[]>([]),[error,setError]=useState(''),[action,setAction]=useState<any>(null),[busy,setBusy]=useState(false)
 const from=month
 async function load(){setRules(await api(`/recurrences?from_month=${from}-01&months=12`))}
 useEffect(()=>{load().catch(cause=>setError((cause as Error).message))},[from,refresh])
 async function execute(path:string,method:string,body?:unknown){setBusy(true);setAction((current:any)=>({...current,error:''}));try{await createOperation(path,method,body)();await load();onChanged();setAction(null)}catch(cause){setAction((current:any)=>({...current,error:(cause as Error).message}))}finally{setBusy(false)}}
 return <section style={{marginTop:28}}><h2>Contas recorrentes</h2><p>Ajuste valores mensais ou encerre as próximas cobranças.</p>{error&&<div role="alert" className="error">{error}</div>}
  <div className="grid two">{rules.map(rule=><section className="panel" key={rule.id}><div className="row spread"><h3>{rule.description}</h3><span className="badge">{rule.variable?'Variável':'Fixa'}</span></div><p>{money(rule.amount_cents)} · vence dia {rule.due_day}</p>{rule.end_month?<small>Encerrada a partir de {monthLabel(rule.end_month.slice(0,7))}</small>:<button onClick={()=>setAction({kind:'end',rule,month:from,error:''})}>Encerrar recorrência</button>}<button style={{marginTop:12}} onClick={()=>setAction({kind:'delete',rule,error:''})}>Excluir recorrência</button><details style={{marginTop:14}}><summary>Valores por mês</summary>{rule.occurrences.map((occurrence:any)=><div className="row spread" key={occurrence.id} style={{marginTop:8}}><small>{monthLabel(occurrence.month.slice(0,7))} · {money(occurrence.amount_cents)} {occurrence.estimated?'(estimado)':''}</small><button onClick={()=>setAction({kind:'amount',occurrence,value:(occurrence.amount_cents/100).toFixed(2),error:''})}>Ajustar valor</button></div>)}</details></section>)}</div>{!rules.length&&<p>Aluguel, energia e internet podem entrar automaticamente no seu planejamento.</p>}
  {action?.kind==='amount'&&<Modal open onClose={()=>setAction(null)} busy={busy}><ModalHeader>Ajustar valor</ModalHeader><ModalBody><label>Valor da conta (R$)<input type="number" min="0.01" step="0.01" value={action.value} onChange={event=>setAction({...action,value:event.target.value})}/></label><ModalFormError message={action.error}/></ModalBody><ModalFooter><button onClick={()=>setAction(null)}>Cancelar</button><button className="primary" onClick={()=>execute(`/occurrences/${action.occurrence.id}`,'PATCH',{version:action.occurrence.version,amount_cents:cents(action.value)})}>{busy?'Salvando…':'Salvar valor'}</button></ModalFooter></Modal>}
  {action?.kind==='end'&&<Modal open onClose={()=>setAction(null)} busy={busy}><ModalHeader>Encerrar recorrência</ModalHeader><ModalBody><p>As ocorrências anteriores serão preservadas.</p><label>Encerrar a partir de<input type="month" value={action.month} onChange={event=>setAction({...action,month:event.target.value})}/></label><ModalFormError message={action.error}/></ModalBody><ModalFooter><button onClick={()=>setAction(null)}>Cancelar</button><button className="primary" onClick={()=>execute(`/recurrences/${action.rule.id}/end`,'POST',{version:action.rule.version,end_month:action.month+'-01'})}>{busy?'Salvando…':'Confirmar encerramento'}</button></ModalFooter></Modal>}
  {action?.kind==='delete'&&<Modal open onClose={()=>setAction(null)} busy={busy}><ConfirmStep title="Excluir recorrência?" description={`A recorrência “${action.rule.description}” e suas ocorrências serão excluídas. Pagamentos registrados precisam ser reabertos antes.`} confirmLabel={busy?'Excluindo…':'Excluir recorrência'} onCancel={()=>setAction(null)} onConfirm={()=>execute(`/recurrences/${action.rule.id}?version=${action.rule.version}&confirm=true`,'DELETE')}/><ModalFormError message={action.error}/></Modal>}
 </section>
}
