import {test,expect} from '@playwright/test'
import {login} from './helpers'

test('ENTRY three types share one entry and support sequential entry',async({page})=>{
 await page.setViewportSize({width:390,height:900});await login(page)
 await page.getByLabel('Competência',{exact:true}).fill('2026-10')
 await page.getByRole('button',{name:'Cartões',exact:true}).click()
 await page.getByRole('button',{name:'Adicionar despesa',exact:true}).click()
 await page.getByRole('button',{name:/Conta recorrente Aluguel/}).click()
 await expect(page.getByLabel('Competência inicial')).toHaveValue('2026-10')
 await page.getByLabel('Descrição',{exact:true}).fill('Aluguel')
 await page.getByLabel('Valor da parcela ou conta (R$)').fill('1600')
 await page.getByRole('button',{name:'Salvar e adicionar outra',exact:true}).click()
 await expect(page.getByRole('status')).toContainText('Despesa salva')
 await expect(page.getByLabel('Descrição',{exact:true})).toHaveValue('')
 await expect(page.getByRole('heading',{name:'Cartões',exact:true})).toBeVisible()
 await page.getByRole('button',{name:'← Trocar tipo de despesa',exact:true}).click()
 await page.getByRole('button',{name:/Parcelas em andamento Uma compra/}).click()
 await page.getByLabel('Descrição',{exact:true}).fill('Panelas')
 await page.getByLabel('Valor da parcela ou conta (R$)').fill('43.51')
 await page.getByLabel('Parcelas ainda abertas').fill('10-12')
 await page.getByRole('button',{name:'Conferir parcelas restantes',exact:true}).click()
 await expect(page.getByText('10/12 · outubro de 2026',{exact:true})).toBeVisible()
 await expect(page.getByText('12/12 · dezembro de 2026',{exact:true})).toBeVisible()
 await page.getByRole('button',{name:'Salvar e adicionar outra',exact:true}).click()
 await expect(page.getByLabel('Descrição',{exact:true})).toHaveValue('')
 await page.getByRole('button',{name:'← Trocar tipo de despesa',exact:true}).click()
 await page.getByRole('button',{name:/Compra ou despesa Uma compra nova/}).click()
 await page.getByLabel('Descrição',{exact:true}).fill('Mercado')
 await page.getByLabel('Valor total (R$)').fill('100')
 await expect(page.getByLabel('Primeira competência')).toHaveValue('2026-10')
 await page.getByRole('button',{name:'Conferir parcelas',exact:true}).click()
 await page.getByRole('button',{name:'Salvar e adicionar outra',exact:true}).click()
 await expect(page.getByLabel('Descrição',{exact:true})).toHaveValue('')
 await expect(page.getByRole('status')).toContainText('Despesa salva')
 await page.getByRole('button',{name:'Fechar',exact:true}).click()
 await page.getByRole('button',{name:'Resumo',exact:true}).click()
 await expect(page.getByTestId('expected')).toContainText('1.743,51')
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true)
})
