import {test,expect} from '@playwright/test'
import {login} from './helpers'

test('ENTRY three types share one entry and support sequential entry',async({page})=>{
 await page.setViewportSize({width:390,height:900});await login(page)
 await page.getByLabel('Competência',{exact:true}).fill('2026-10')
 await page.getByRole('button',{name:'Cartões',exact:true}).click()
 await page.getByRole('button',{name:'Adicionar despesa',exact:true}).click()
 await page.getByRole('button',{name:/Conta recorrente Aluguel/}).click()
 await expect(page.getByLabel('Competência inicial')).toHaveValue('2026-10')
 await page.getByLabel('Descrição',{exact:true}).fill('Aluguel')
 await page.getByLabel('Valor da parcela ou conta (R$)').fill('1600')
 await page.getByRole('button',{name:'Salvar e adicionar outra',exact:true}).click()
 await expect(page.getByRole('status')).toContainText('Despesa salva')
 await expect(page.getByLabel('Descrição',{exact:true})).toHaveValue('')
 await expect(page.getByRole('heading',{name:'Cartões',exact:true})).toBeVisible()
 await page.getByRole('button',{name:'← Trocar tipo de despesa',exact:true}).click()
 await page.getByRole('button',{name:/Parcelas em andamento Uma compra/}).click()
 await page.getByLabel('Descrição',{exact:true}).fill('Panelas')
 await page.getByLabel('Valor da parcela ou conta (R$)').fill('43.51')
 await page.getByLabel('Parcelas ainda abertas').fill('10-12')
 await page.getByRole('button',{name:'Conferir parcelas restantes',exact:true}).click()
 await expect(page.getByText('10/12 · outubro de 2026',{exact:true})).toBeVisible()
 await expect(page.getByText('12/12 · dezembro de 2026',{exact:true})).toBeVisible()
 await page.getByRole('button',{name:'Salvar e adicionar outra',exact:true}).click()
 await expect(page.getByLabel('Descrição',{exact:true})).toHaveValue('')
 await page.getByRole('button',{name:'← Trocar tipo de despesa',exact:true}).click()
 await page.getByRole('button',{name:/Compra ou despesa Uma compra nova/}).click()
 await page.getByLabel('Descrição',{exact:true}).fill('Mercado')
 await page.getByLabel('Valor total (R$)').fill('100')
 await expect(page.getByLabel('Primeira competência')).toHaveValue('2026-10')
 await page.getByRole('button',{name:'Conferir parcelas',exact:true}).click()
 await page.getByRole('button',{name:'Salvar e adicionar outra',exact:true}).click()
 await expect(page.getByLabel('Descrição',{exact:true})).toHaveValue('')
 await expect(page.getByRole('status')).toContainText('Despesa salva')
 await page.getByRole('button',{name:'Fechar',exact:true}).click()
 await page.getByRole('button',{name:'Resumo',exact:true}).click()
 await expect(page.getByTestId('expected')).toContainText('1.743,51')
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true)
})

test('NAV summary highlights pending while entries search all monthly expenses',async({page})=>{
 await login(page)
 await page.evaluate(async()=>{
  const me=await(await fetch('/api/v1/auth/me')).json(),csrf=await(await fetch('/api/v1/auth/csrf')).json()
  const send=async(path:string,body:any)=>(await fetch('/api/v1'+path,{method:'POST',headers:{'Content-Type':'application/json','X-CSRF-Token':csrf.csrf_token,'Idempotency-Key':crypto.randomUUID()},body:JSON.stringify(body)})).json()
  for(let n=1;n<=7;n++){
   const c=await send('/commitments',{description:'Despesa '+n,buyer_id:me.user.id,purchased_at:'2026-10-01',first_month:'2026-10-01',total_cents:10000,count:1,shares:[{user_id:me.user.id,weight:10000}]})
   if(n===1)await send(`/installments/${c.installments[0].id}/pay`,{version:1,paid_at:'2026-10-05'})
  }
 })
 await page.reload();await page.getByLabel('Competência',{exact:true}).fill('2026-10')
 await expect(page.getByTestId('expected')).toContainText('700,00')
 await expect(page.locator('.desktop-only tbody tr')).toHaveCount(5)
 await expect(page.getByLabel('Pesquisar lançamentos')).toHaveCount(0)
 await page.getByRole('button',{name:'Ver todos os lançamentos',exact:true}).click()
 await expect(page.getByRole('heading',{name:'Lançamentos',exact:true})).toBeVisible()
 await expect(page.getByLabel('Competência',{exact:true})).toHaveValue('2026-10')
 await expect(page.getByTestId('expected')).toHaveCount(0)
 await expect(page.locator('.desktop-only tbody tr')).toHaveCount(7)
 await page.getByLabel('Pesquisar lançamentos').fill('Despesa 1')
 await expect(page.locator('.desktop-only tbody tr')).toHaveCount(1)
 await expect(page.locator('.desktop-only tbody')).toContainText('Pago')
 await page.getByRole('button',{name:'A pagar',exact:true}).click()
 await expect(page.locator('.desktop-only tbody tr')).toHaveCount(0)
 await page.getByLabel('Pesquisar lançamentos').fill('')
 await expect(page.locator('.desktop-only tbody tr')).toHaveCount(6)
 await expect(page.getByRole('heading',{name:'Contas recorrentes',exact:true})).toBeVisible()
 await page.getByRole('button',{name:'Planejamento',exact:true}).click()
 await expect(page.getByRole('heading',{name:'Contas recorrentes',exact:true})).toHaveCount(0)
 await expect(page.getByRole('button',{name:'Trazer parcelas da planilha',exact:true})).toHaveCount(0)
 await expect(page.getByRole('button',{name:'Adicionar despesa',exact:true})).toBeVisible()
})
